"""Canonical deep public seams for Paper-I RA-ADAPT and Append-ADAPT."""

from __future__ import annotations

from typing import Any

from pipelines.static_adapt.adaptive_phase_contracts import (
    ADAPTIVE_HORIZON_POLICY_EXACT_TARGET_V1,
    ADAPTIVE_HORIZON_POLICY_MAXIMUM_V1,
    ADAPTIVE_PHASE3_NO_POSITIVE_POLICY_RAISE_V1,
    ADAPTIVE_PHASE3_NO_POSITIVE_POLICY_TYPED_TERMINAL_V1,
    ADAPTIVE_PHASE3_NO_POSITIVE_TERMINAL_OUTCOME_V1,
)
from pipelines.static_adapt.ra_adapt.adapters import (
    CandidateRepresentationAdapter,
    GlobalSinglePauliWordCandidateAdapter,
    GlobalSingletonGradientPhase0CandidateAdapter,
    H2OLinearFDSinglePauliWordCandidateAdapter,
    H2OLinearFDSymmetryCompleteCandidateAdapter,
    MacroCandidateAdapter,
    MacroGradientPhase0CandidateAdapter,
    MacroGradientPhase0ThenSingletonCandidateAdapter,
    MacroThenSingletonPhaseICandidateAdapter,
    SinglePauliWordCandidateAdapter,
)
from pipelines.static_adapt.ra_adapt.contracts import (
    AppendAdaptRequest,
    AppendAdaptResult,
    CandidateInventoryLineageReceipt,
    CandidateInventoryLineageRow,
    CandidateLineageReceipt,
    PhaseIIIMultiplierContract,
    PhaseIIIStabilizationReceipt,
    PolicyEchoReceipt,
    PoolInventoryReceipt,
    RAAdaptOperationalControls,
    RAAdaptRequest,
    RAAdaptResult,
    ResolvedRAAdaptProtocol,
)
from pipelines.static_adapt.ra_adapt.engine import run_ra_adapt
from pipelines.static_adapt.ra_adapt.adaptive_phase_shortlist import (
    ADAPTIVE_PHASE123_SHORTLIST_POLICY_V1,
    AdaptivePhaseCandidateScore,
    AdaptivePhaseSelectionMappingReceipt,
    AdaptivePhaseShortlistReceipt,
    adaptive_phase_record_id,
    adaptive_phase_selection_receipt_from_mapping,
    adaptive_phase_shortlist_receipt_from_mapping,
    select_adaptive_phase_shortlist,
    validate_adaptive_phase_shortlist_receipt,
)
from pipelines.static_adapt.ra_adapt.semantic_closure_routes import (
    PAPER_I_RA_ALL_PHASE_ADAPTIVE_NATURAL_TERMINAL_IMPLEMENTATION_VERSION_V2,
    PAPER_I_RA_ALL_PHASE_ADAPTIVE_NATURAL_TERMINAL_NATIVE_BUNDLE_ID_V2,
    PAPER_I_RA_ALL_PHASE_ADAPTIVE_SHORTLIST_V1,
    PAPER_I_RA_ALL_PHASE_ADAPTIVE_SHORTLIST_FORCED_K50_V1,
    PAPER_I_RA_ALL_PHASE_ADAPTIVE_SHORTLIST_NATURAL_TERMINAL_V2,
    PAPER_I_RA_ALL_PHASE_POSITION_ADAPTIVE_NATURAL_TERMINAL_IMPLEMENTATION_VERSION_V2,
    PAPER_I_RA_ALL_PHASE_POSITION_ADAPTIVE_NATURAL_TERMINAL_NATIVE_BUNDLE_ID_V2,
    PAPER_I_RA_ALL_PHASE_POSITION_ADAPTIVE_SHORTLIST_V1,
    PAPER_I_RA_ALL_PHASE_POSITION_ADAPTIVE_SHORTLIST_FORCED_K50_V1,
    PAPER_I_RA_ALL_PHASE_POSITION_ADAPTIVE_SHORTLIST_NATURAL_TERMINAL_V2,
    PAPER_I_RA_CANONICAL_REGIME_IDS,
    PAPER_I_RA_PHASE0_GRADIENT_FIXED24,
    PAPER_I_RA_PHASE0_GRADIENT_ADAPTIVE_V2,
    PAPER_I_RA_PHASE0_GRADIENT_FIXED24_V2,
    PAPER_I_RA_PHASE0_PROXY_ADAPTIVE,
    PAPER_I_RA_PHASE0_PROXY_ADAPTIVE_V2,
    PAPER_I_RA_PHASE0_PROXY_FIXED24_V2,
    PAPER_I_RA_PHASE0_PROXY_FIXED24_SHADOW,
    PAPER_I_RA_PHASE0_POSITION_GRADIENT_ADAPTIVE_V1,
    PAPER_I_RA_PHASE0_POSITION_GRADIENT_FIXED24_V1,
    PAPER_I_RA_PHASE0_POSITION_PROXY_ADAPTIVE_V1,
    PAPER_I_RA_PHASE0_POSITION_PROXY_FIXED24_V1,
    PAPER_I_RA_PHASE0_POSITION_ROUTE_VARIANTS,
    PAPER_I_RA_PHASE0_V2_ROUTE_VARIANTS,
    PAPER_I_RA_PHASE3_NATURAL_TERMINAL_ROUTE_VARIANTS,
    PAPER_I_RA_PHASE123_QISKIT_COMPILE_SCOPE,
    PAPER_I_RA_SEMANTIC_ALGORITHM_IDS,
    PAPER_I_RA_SEMANTIC_IMPLEMENTATION_VERSION,
    PAPER_I_RA_SEMANTIC_IMPLEMENTATION_VERSION_V2,
    PaperIRASemanticClosureGlobalSingletonCandidateAdapter,
    PaperIRASemanticClosureRouteIdentity,
    build_paper_i_ra_strong_weak_always_k5_request,
    build_paper_i_ra_strong_weak_plateau_k5_request,
    build_paper_i_ra_strong_weak_nph3_problem,
    build_paper_i_ra_all_phase_adaptive_request,
    build_paper_i_ra_all_phase_adaptive_forced_k50_request,
    build_paper_i_ra_all_phase_adaptive_natural_terminal_request,
    build_paper_i_ra_all_phase_position_adaptive_request,
    build_paper_i_ra_all_phase_position_adaptive_forced_k50_request,
    build_paper_i_ra_all_phase_position_adaptive_natural_terminal_request,
    build_paper_i_ra_hh_regime_problem,
    materialize_paper_i_ra_semantic_protocol,
    materialize_paper_i_ra_strong_weak_always_k5_protocol,
    preflight_paper_i_ra_semantic,
    preflight_paper_i_ra_strong_weak_always_k5,
    preflight_paper_i_ra_strong_weak_plateau_k5,
    project_approved_phase0_ablation,
    semantic_closure_source_implementation_inventory,
    semantic_closure_route_identity,
    validate_semantic_phase3_no_positive_terminal_receipt,
    validate_semantic_phase3_natural_terminal_route_contract,
)
from pipelines.static_adapt.ra_adapt.l3_page12 import (
    PAPER_I_L3_PAGE12_SOURCE_LOCK_KEY,
    PaperIL3Page12GlobalSingletonGradientPhase0CandidateAdapter,
    build_paper_i_l3_page12_problem,
    build_paper_i_l3_page12_request,
    paper_i_l3_page12_application_source_contract,
)
from pipelines.static_adapt.ra_adapt.pure_hubbard_noise_page12 import (
    PAPER_I_PURE_HUBBARD_NOISE_PAGE12_SOURCE_LOCK_KEY,
    PaperIPureHubbardNoisePage12CandidateAdapter,
    build_paper_i_pure_hubbard_noise_page12_problem,
    build_paper_i_pure_hubbard_noise_page12_request,
    paper_i_pure_hubbard_noise_page12_application_source_contract,
)
from pipelines.static_adapt.ra_adapt.campaign import (
    PaperICampaignContractError,
    PaperICampaignPlan,
    PaperILocalExecutionAuthorization,
    authorize_paper_i_campaign,
    execute_paper_i_campaign,
    materialize_paper_i_campaign,
    retry_paper_i_campaign_qiskit_observation,
)


def run_append_adapt(problem: Any, request: Any = None) -> AppendAdaptResult:
    """Load the independent conventional selector only when requested."""

    from pipelines.static_adapt.ra_adapt.append import (
        run_append_adapt as _run_append_adapt,
    )

    return _run_append_adapt(problem, request)


__all__ = [
    "ADAPTIVE_PHASE123_SHORTLIST_POLICY_V1",
    "ADAPTIVE_HORIZON_POLICY_EXACT_TARGET_V1",
    "ADAPTIVE_HORIZON_POLICY_MAXIMUM_V1",
    "ADAPTIVE_PHASE3_NO_POSITIVE_POLICY_RAISE_V1",
    "ADAPTIVE_PHASE3_NO_POSITIVE_POLICY_TYPED_TERMINAL_V1",
    "ADAPTIVE_PHASE3_NO_POSITIVE_TERMINAL_OUTCOME_V1",
    "AdaptivePhaseCandidateScore",
    "AdaptivePhaseSelectionMappingReceipt",
    "AdaptivePhaseShortlistReceipt",
    "AppendAdaptRequest",
    "AppendAdaptResult",
    "CandidateInventoryLineageReceipt",
    "CandidateInventoryLineageRow",
    "CandidateLineageReceipt",
    "CandidateRepresentationAdapter",
    "GlobalSinglePauliWordCandidateAdapter",
    "GlobalSingletonGradientPhase0CandidateAdapter",
    "H2OLinearFDSinglePauliWordCandidateAdapter",
    "H2OLinearFDSymmetryCompleteCandidateAdapter",
    "MacroCandidateAdapter",
    "MacroGradientPhase0CandidateAdapter",
    "MacroGradientPhase0ThenSingletonCandidateAdapter",
    "MacroThenSingletonPhaseICandidateAdapter",
    "PaperICampaignContractError",
    "PaperICampaignPlan",
    "PaperILocalExecutionAuthorization",
    "PAPER_I_L3_PAGE12_SOURCE_LOCK_KEY",
    "PAPER_I_PURE_HUBBARD_NOISE_PAGE12_SOURCE_LOCK_KEY",
    "PAPER_I_RA_PHASE0_GRADIENT_FIXED24",
    "PAPER_I_RA_ALL_PHASE_ADAPTIVE_NATURAL_TERMINAL_IMPLEMENTATION_VERSION_V2",
    "PAPER_I_RA_ALL_PHASE_ADAPTIVE_NATURAL_TERMINAL_NATIVE_BUNDLE_ID_V2",
    "PAPER_I_RA_ALL_PHASE_ADAPTIVE_SHORTLIST_V1",
    "PAPER_I_RA_ALL_PHASE_ADAPTIVE_SHORTLIST_FORCED_K50_V1",
    "PAPER_I_RA_ALL_PHASE_ADAPTIVE_SHORTLIST_NATURAL_TERMINAL_V2",
    "PAPER_I_RA_ALL_PHASE_POSITION_ADAPTIVE_NATURAL_TERMINAL_IMPLEMENTATION_VERSION_V2",
    "PAPER_I_RA_ALL_PHASE_POSITION_ADAPTIVE_NATURAL_TERMINAL_NATIVE_BUNDLE_ID_V2",
    "PAPER_I_RA_ALL_PHASE_POSITION_ADAPTIVE_SHORTLIST_V1",
    "PAPER_I_RA_ALL_PHASE_POSITION_ADAPTIVE_SHORTLIST_FORCED_K50_V1",
    "PAPER_I_RA_ALL_PHASE_POSITION_ADAPTIVE_SHORTLIST_NATURAL_TERMINAL_V2",
    "PAPER_I_RA_CANONICAL_REGIME_IDS",
    "PAPER_I_RA_PHASE0_GRADIENT_ADAPTIVE_V2",
    "PAPER_I_RA_PHASE0_GRADIENT_FIXED24_V2",
    "PAPER_I_RA_PHASE0_PROXY_ADAPTIVE",
    "PAPER_I_RA_PHASE0_PROXY_ADAPTIVE_V2",
    "PAPER_I_RA_PHASE0_PROXY_FIXED24_V2",
    "PAPER_I_RA_PHASE0_PROXY_FIXED24_SHADOW",
    "PAPER_I_RA_PHASE0_POSITION_GRADIENT_ADAPTIVE_V1",
    "PAPER_I_RA_PHASE0_POSITION_GRADIENT_FIXED24_V1",
    "PAPER_I_RA_PHASE0_POSITION_PROXY_ADAPTIVE_V1",
    "PAPER_I_RA_PHASE0_POSITION_PROXY_FIXED24_V1",
    "PAPER_I_RA_PHASE0_POSITION_ROUTE_VARIANTS",
    "PAPER_I_RA_PHASE0_V2_ROUTE_VARIANTS",
    "PAPER_I_RA_PHASE3_NATURAL_TERMINAL_ROUTE_VARIANTS",
    "PAPER_I_RA_PHASE123_QISKIT_COMPILE_SCOPE",
    "PAPER_I_RA_SEMANTIC_ALGORITHM_IDS",
    "PAPER_I_RA_SEMANTIC_IMPLEMENTATION_VERSION",
    "PAPER_I_RA_SEMANTIC_IMPLEMENTATION_VERSION_V2",
    "PaperIL3Page12GlobalSingletonGradientPhase0CandidateAdapter",
    "PaperIPureHubbardNoisePage12CandidateAdapter",
    "PaperIRASemanticClosureGlobalSingletonCandidateAdapter",
    "PaperIRASemanticClosureRouteIdentity",
    "PhaseIIIMultiplierContract",
    "PhaseIIIStabilizationReceipt",
    "PolicyEchoReceipt",
    "PoolInventoryReceipt",
    "RAAdaptOperationalControls",
    "RAAdaptRequest",
    "RAAdaptResult",
    "ResolvedRAAdaptProtocol",
    "SinglePauliWordCandidateAdapter",
    "authorize_paper_i_campaign",
    "adaptive_phase_record_id",
    "adaptive_phase_selection_receipt_from_mapping",
    "adaptive_phase_shortlist_receipt_from_mapping",
    "build_paper_i_ra_all_phase_adaptive_request",
    "build_paper_i_ra_all_phase_adaptive_forced_k50_request",
    "build_paper_i_ra_all_phase_adaptive_natural_terminal_request",
    "build_paper_i_ra_all_phase_position_adaptive_request",
    "build_paper_i_ra_all_phase_position_adaptive_forced_k50_request",
    "build_paper_i_ra_all_phase_position_adaptive_natural_terminal_request",
    "build_paper_i_ra_hh_regime_problem",
    "build_paper_i_l3_page12_problem",
    "build_paper_i_l3_page12_request",
    "build_paper_i_pure_hubbard_noise_page12_problem",
    "build_paper_i_pure_hubbard_noise_page12_request",
    "build_paper_i_ra_strong_weak_always_k5_request",
    "build_paper_i_ra_strong_weak_plateau_k5_request",
    "build_paper_i_ra_strong_weak_nph3_problem",
    "execute_paper_i_campaign",
    "materialize_paper_i_campaign",
    "materialize_paper_i_ra_semantic_protocol",
    "materialize_paper_i_ra_strong_weak_always_k5_protocol",
    "paper_i_l3_page12_application_source_contract",
    "paper_i_pure_hubbard_noise_page12_application_source_contract",
    "preflight_paper_i_ra_semantic",
    "preflight_paper_i_ra_strong_weak_always_k5",
    "preflight_paper_i_ra_strong_weak_plateau_k5",
    "project_approved_phase0_ablation",
    "retry_paper_i_campaign_qiskit_observation",
    "run_append_adapt",
    "run_ra_adapt",
    "select_adaptive_phase_shortlist",
    "semantic_closure_route_identity",
    "semantic_closure_source_implementation_inventory",
    "validate_adaptive_phase_shortlist_receipt",
    "validate_semantic_phase3_no_positive_terminal_receipt",
    "validate_semantic_phase3_natural_terminal_route_contract",
]
