#!/usr/bin/env python3
"""Emit Paper III manuscript table fragments from the evidence JSONs.

Generates LaTeX fragments under ``MATH/paper_details/generated/`` for
\\input into the manuscript's results section. Deterministic and
regenerable: every number is read from the committed evidence JSONs (the
same sources as the results-consolidation Markdown), so reruns of any
driver refresh the manuscript tables without hand transcription. The
fragments are statevector-diagnostic evidence and are labeled as such;
they complement, not replace, the locked CHTC production matrix
placeholders. Reporting only; never feeds controller decisions.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Sequence

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

DIAG = REPO_ROOT / "output/diagnostics"
DEFAULT_OUTPUT_DIR = REPO_ROOT / "MATH/paper_details/generated"

MULTIROOT_JSON = DIAG / "paper_iii_multiroot_sweep_20260818_v1/multiroot_sweep_b60_retained.json"
COMPARATORS_JSON = DIAG / "paper_iii_cost_frontier_arms_20260818_v1/comparator_arms_summary.json"
EXCHANGE_DIMER_JSON = (
    DIAG / "paper_iii_cost_frontier_arms_20260818_v1/exchange_maintenance_evidence.json"
)
PEIERLS_JSON = DIAG / "paper_iii_peierls_pilot_20260819_v1/peierls_pilot_v4.json"

_ARM_LABELS = {
    "fixed_linear_response_complete": "fixed linear-response class (complete)",
    "geometry_alpha1_R6": r"geometry-selected ($\alpha=1$, $R=6$)",
    "exchange_dominance_R6": "geometry + certified exchange",
}


def _load(path: Path) -> dict[str, Any]:
    if not path.is_file():
        raise FileNotFoundError(f"evidence file missing: {path}")
    return json.loads(path.read_text(encoding="utf-8"))


def _sci(value: Any) -> str:
    if value is None:
        return "--"
    mantissa, exponent = f"{float(value):.1e}".split("e")
    return rf"${mantissa}\times10^{{{int(exponent)}}}$"


def _escape(text: Any) -> str:
    return str(text).replace("_", r"\_")


def _fragment_header(sources: Sequence[Path]) -> str:
    lines = [
        "% AUTO-GENERATED by pipelines/reporting/build_paper_iii_tex_fragments.py",
        "% Do not edit by hand; rerun the generator after refreshing evidence.",
    ]
    lines.extend(f"% source: {path.relative_to(REPO_ROOT)}" for path in sources)
    return "\n".join(lines) + "\n"


def build_multiroot_fragment() -> str:
    payload = _load(MULTIROOT_JSON)
    lines = [_fragment_header([MULTIROOT_JSON])]
    lines.append(r"\begin{widetext}")
    lines.append(
        r"\inlinetablecaption{tab:qse_multiroot_diag}{Statevector-diagnostic "
        r"multi-root accuracy over the six Paper-I Hubbard--Holstein regimes "
        r"(lowest six excitations, exact sector-restricted references, "
        r"budget 60, Ky Fan $R=6$ objective). Cost is compiled two-qubit "
        r"gate count under the \texttt{two\_qubit\_only\_v1} scalarization.}"
    )
    lines.append(r"\begin{center}")
    lines.append(r"\scriptsize")
    lines.append(r"\begin{ruledtabular}")
    lines.append(r"\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}llcc@{}}")
    lines.append(
        r"Regime & Method & compiled 2Q & $\max_{r\le 6}|\Delta E_r|$ \\"
    )
    lines.append(r"\colrule")
    for regime, record in payload["regimes"].items():
        for arm_key, arm_label in _ARM_LABELS.items():
            arm = record["arms"].get(arm_key)
            if arm is None:
                continue
            errors = [e for e in arm["root_abs_errors"] if e is not None]
            lines.append(
                rf"{_escape(regime)} & {arm_label} & {arm['total_2q']:.0f} & "
                rf"{_sci(max(errors) if errors else None)} \\"
            )
        lines.append(r"\colrule")
    if lines[-1] == r"\colrule":
        lines.pop()
    lines.append(r"\end{tabular*}")
    lines.append(r"\end{ruledtabular}")
    lines.append(r"\end{center}")
    lines.append(r"\end{widetext}")
    return "\n".join(lines) + "\n"


def build_comparator_fragment() -> str:
    comparators = _load(COMPARATORS_JSON)
    exchange = _load(EXCHANGE_DIMER_JSON)
    reference = float(exchange["reference_root0"])
    lines = [_fragment_header([COMPARATORS_JSON, EXCHANGE_DIMER_JSON])]
    lines.append(
        r"\inlinetablecaption{tab:qse_comparators_diag}{Statevector-diagnostic "
        r"cross-family comparison at the weak-coupling dimer point: first-"
        r"excitation error versus compiled two-qubit cost. The Krylov arm "
        r"uses a Hamiltonian-residual kick, exact propagation, and "
        r"Krylov-favoring state-preparation costing.}"
    )
    lines.append(r"\begin{center}")
    lines.append(r"\scriptsize")
    lines.append(r"\begin{ruledtabular}")
    lines.append(r"\begin{tabular}{lcc}")
    lines.append(r"Method & compiled 2Q & $|\Delta E_1|$ \\")
    lines.append(r"\colrule")
    geo = exchange["runs"]["from_geometry_alpha1"]
    lines.append(
        rf"geometry-selected ($\alpha=1$, $k=20$) & "
        rf"{geo['initial']['total_compiled_cost']:.0f} & "
        rf"{_sci(abs(geo['initial']['root0_energy'] - reference))} \\"
    )
    lines.append(
        rf"geometry + certified exchange & "
        rf"{geo['final']['total_compiled_cost']:.0f} & "
        rf"{_sci(abs(geo['final']['root0_energy'] - reference))} \\"
    )
    for name, arm in comparators["fixed_class_arms"].items():
        lines.append(
            rf"fixed class: {_escape(name)} ({arm['class_size']} records) & "
            rf"{arm['total_2q_graph_span']:.0f} & {_sci(arm['abs_err_vs_reference'])} \\"
        )
    envelope = comparators["krylov_arm"]["best_per_cost_envelope"]
    if envelope:
        best = envelope[-1]
        lines.append(
            rf"real-time Krylov (best, $K={best['krylov_dimension']}$) & "
            rf"{best['cum_2q_graph_span']:.0f} & {_sci(best['abs_err_vs_reference'])} \\"
        )
    lines.append(r"\end{tabular}")
    lines.append(r"\end{ruledtabular}")
    lines.append(r"\end{center}")
    return "\n".join(lines) + "\n"


def build_peierls_fragment() -> str:
    payload = _load(PEIERLS_JSON)
    lines = [_fragment_header([PEIERLS_JSON])]
    lines.append(
        r"\inlinetablecaption{tab:qse_peierls_diag}{Statevector-diagnostic "
        r"generality check on the Peierls--Hubbard dimer (bond-coupled "
        r"phonon, $n_{\rm ph}=3$): maximum error over the lowest six "
        r"excitations. The naive fixed class misses the spin-structure "
        r"directions required by bond coupling.}"
    )
    lines.append(r"\begin{center}")
    lines.append(r"\scriptsize")
    lines.append(r"\begin{ruledtabular}")
    lines.append(r"\begin{tabular}{llcc}")
    lines.append(r"Coupling point & Method & compiled 2Q & $\max_{r\le 6}|\Delta E_r|$ \\")
    lines.append(r"\colrule")
    for regime, record in payload["regimes"].items():
        for arm_key, arm_label in _ARM_LABELS.items():
            arm = record["arms"].get(arm_key)
            if arm is None:
                continue
            errors = [e for e in arm["root_abs_errors"] if e is not None]
            lines.append(
                rf"{_escape(regime)} & {arm_label} & {arm['total_2q']:.0f} & "
                rf"{_sci(max(errors) if errors else None)} \\"
            )
        lines.append(r"\colrule")
    if lines[-1] == r"\colrule":
        lines.pop()
    lines.append(r"\end{tabular}")
    lines.append(r"\end{ruledtabular}")
    lines.append(r"\end{center}")
    return "\n".join(lines) + "\n"


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    args = parser.parse_args(argv)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    fragments = {
        "paper_iii_multiroot_table.tex": build_multiroot_fragment(),
        "paper_iii_comparator_table.tex": build_comparator_fragment(),
        "paper_iii_peierls_table.tex": build_peierls_fragment(),
    }
    for name, content in fragments.items():
        (args.output_dir / name).write_text(content, encoding="utf-8")
        print(f"wrote {args.output_dir / name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
