#!/usr/bin/env python3
"""Emit Paper III manuscript table fragments from the evidence JSONs.

Generates LaTeX fragments under ``MATH/paper_details/generated/`` for
\\input into the manuscript's results section. Deterministic and
regenerable: every number is read from the committed evidence JSONs (the
same sources as the results-consolidation Markdown), so reruns of any
driver refresh the manuscript tables without hand transcription. The
fragments are statevector-diagnostic evidence and are labeled as such;
they complement, not replace, the locked CHTC production matrix
placeholders. Reporting only; never feeds controller decisions.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Sequence

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

DIAG = REPO_ROOT / "output/diagnostics"
DEFAULT_OUTPUT_DIR = REPO_ROOT / "MATH/paper_details/generated"

MULTIROOT_JSON = DIAG / "paper_iii_multiroot_sweep_20260818_v1/multiroot_sweep_epsstop.json"
COMPARATORS_JSON = DIAG / "paper_iii_cost_frontier_arms_20260818_v1/comparator_arms_summary.json"
EXCHANGE_DIMER_JSON = (
    DIAG / "paper_iii_cost_frontier_arms_20260818_v1/exchange_maintenance_evidence.json"
)
PEIERLS_JSON = DIAG / "paper_iii_peierls_pilot_20260819_v1/peierls_pilot_v4.json"
COMPARATOR_MATRIX_JSON = (
    DIAG / "paper_iii_comparator_matrix_20260819_v1/comparator_matrix.json"
)
DRIVEN_JSON = DIAG / "paper_iii_driven_dynamics_20260819_v1/driven_dynamics.json"
ADAPTIVE_JSON = DIAG / "paper_iii_driven_dynamics_20260819_v1/adaptive_dynamics.json"
ABLATION_JSON = DIAG / "paper_iii_score_ablation_20260819_v1/score_ablation.json"

_ARM_LABELS = {
    "fixed_linear_response_complete": "fixed linear-response class (complete)",
    "geometry_alpha1_R6": r"geometry-selected ($\alpha=1$, $R=6$)",
    "exchange_dominance_R6": "geometry + certified exchange",
}


def _load(path: Path) -> dict[str, Any]:
    if not path.is_file():
        raise FileNotFoundError(f"evidence file missing: {path}")
    return json.loads(path.read_text(encoding="utf-8"))


def _sci(value: Any) -> str:
    if value is None:
        return "--"
    mantissa, exponent = f"{float(value):.1e}".split("e")
    return rf"${mantissa}\times10^{{{int(exponent)}}}$"


def _escape(text: Any) -> str:
    return str(text).replace("_", r"\_")


def _fragment_header(sources: Sequence[Path]) -> str:
    lines = [
        "% AUTO-GENERATED by pipelines/reporting/build_paper_iii_tex_fragments.py",
        "% Do not edit by hand; rerun the generator after refreshing evidence.",
    ]
    lines.extend(f"% source: {path.relative_to(REPO_ROOT)}" for path in sources)
    return "\n".join(lines) + "\n"


def build_multiroot_fragment() -> str:
    payload = _load(MULTIROOT_JSON)
    lines = [_fragment_header([MULTIROOT_JSON])]
    lines.append(r"\begin{widetext}")
    lines.append(
        r"\inlinetablecaption{tab:qse_multiroot_diag}{Statevector-diagnostic "
        r"multi-root accuracy over the six Paper-I Hubbard--Holstein regimes "
        r"(lowest six excitations, exact sector-restricted references, "
        r"residual-norm stop $\varepsilon=10^{-3}$ with a pool-relative "
        r"window-closure test; support size is an output). Cost is compiled two-qubit "
        r"gate count under the \texttt{two\_qubit\_only\_v1} scalarization.}"
    )
    lines.append(r"\begin{center}")
    lines.append(r"\scriptsize")
    lines.append(r"\begin{ruledtabular}")
    lines.append(r"\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}llcc@{}}")
    lines.append(
        r"Regime & Method & compiled 2Q & $\max_{r\le 6}|\Delta E_r|$ \\"
    )
    lines.append(r"\colrule")
    for regime, record in payload["regimes"].items():
        for arm_key, arm_label in _ARM_LABELS.items():
            arm = record["arms"].get(arm_key)
            if arm is None:
                continue
            errors = [e for e in arm["root_abs_errors"] if e is not None]
            lines.append(
                rf"{_escape(regime)} & {arm_label} & {arm['total_2q']:.0f} & "
                rf"{_sci(max(errors) if errors else None)} \\"
            )
        lines.append(r"\colrule")
    if lines[-1] == r"\colrule":
        lines.pop()
    lines.append(r"\end{tabular*}")
    lines.append(r"\end{ruledtabular}")
    lines.append(r"\end{center}")
    lines.append(r"\end{widetext}")
    return "\n".join(lines) + "\n"


def build_comparator_fragment() -> str:
    comparators = _load(COMPARATORS_JSON)
    exchange = _load(EXCHANGE_DIMER_JSON)
    reference = float(exchange["reference_root0"])
    lines = [_fragment_header([COMPARATORS_JSON, EXCHANGE_DIMER_JSON])]
    lines.append(
        r"\inlinetablecaption{tab:qse_comparators_diag}{Statevector-diagnostic "
        r"cross-family comparison at the weak-coupling dimer point: first-"
        r"excitation error versus compiled two-qubit cost. The Krylov arm "
        r"uses a Hamiltonian-residual kick, exact propagation, and "
        r"Krylov-favoring state-preparation costing.}"
    )
    lines.append(r"\begin{center}")
    lines.append(r"\scriptsize")
    lines.append(r"\begin{ruledtabular}")
    lines.append(r"\begin{tabular}{lcc}")
    lines.append(r"Method & compiled 2Q & $|\Delta E_1|$ \\")
    lines.append(r"\colrule")
    geo = exchange["runs"]["from_geometry_alpha1"]
    lines.append(
        rf"geometry-selected ($\alpha=1$, $k=20$) & "
        rf"{geo['initial']['total_compiled_cost']:.0f} & "
        rf"{_sci(abs(geo['initial']['root0_energy'] - reference))} \\"
    )
    lines.append(
        rf"geometry + certified exchange & "
        rf"{geo['final']['total_compiled_cost']:.0f} & "
        rf"{_sci(abs(geo['final']['root0_energy'] - reference))} \\"
    )
    for name, arm in comparators["fixed_class_arms"].items():
        lines.append(
            rf"fixed class: {_escape(name)} ({arm['class_size']} records) & "
            rf"{arm['total_2q_graph_span']:.0f} & {_sci(arm['abs_err_vs_reference'])} \\"
        )
    envelope = comparators["krylov_arm"]["best_per_cost_envelope"]
    if envelope:
        best = envelope[-1]
        lines.append(
            rf"real-time Krylov (best, $K={best['krylov_dimension']}$) & "
            rf"{best['cum_2q_graph_span']:.0f} & {_sci(best['abs_err_vs_reference'])} \\"
        )
    lines.append(r"\end{tabular}")
    lines.append(r"\end{ruledtabular}")
    lines.append(r"\end{center}")
    return "\n".join(lines) + "\n"


def build_peierls_fragment() -> str:
    payload = _load(PEIERLS_JSON)
    lines = [_fragment_header([PEIERLS_JSON])]
    lines.append(
        r"\inlinetablecaption{tab:qse_peierls_diag}{Statevector-diagnostic "
        r"generality check on the Peierls--Hubbard dimer (bond-coupled "
        r"phonon, $n_{\rm ph}=3$): maximum error over the lowest six "
        r"excitations. The naive fixed class misses the spin-structure "
        r"directions required by bond coupling.}"
    )
    lines.append(r"\begin{center}")
    lines.append(r"\scriptsize")
    lines.append(r"\begin{ruledtabular}")
    lines.append(r"\begin{tabular}{llcc}")
    lines.append(r"Coupling point & Method & compiled 2Q & $\max_{r\le 6}|\Delta E_r|$ \\")
    lines.append(r"\colrule")
    for regime, record in payload["regimes"].items():
        for arm_key, arm_label in _ARM_LABELS.items():
            arm = record["arms"].get(arm_key)
            if arm is None:
                continue
            errors = [e for e in arm["root_abs_errors"] if e is not None]
            lines.append(
                rf"{_escape(regime)} & {arm_label} & {arm['total_2q']:.0f} & "
                rf"{_sci(max(errors) if errors else None)} \\"
            )
        lines.append(r"\colrule")
    if lines[-1] == r"\colrule":
        lines.pop()
    lines.append(r"\end{tabular}")
    lines.append(r"\end{ruledtabular}")
    lines.append(r"\end{center}")
    return "\n".join(lines) + "\n"


def build_comparator_matrix_fragment() -> str:
    matrix = _load(COMPARATOR_MATRIX_JSON)
    lines = [_fragment_header([COMPARATOR_MATRIX_JSON])]
    lines.append(r"\begin{widetext}")
    lines.append(
        r"\inlinetablecaption{tab:qse_comparator_matrix}{Cross-family "
        r"comparator matrix on identical Hamiltonians, sectors, and "
        r"references: maximum error over the lowest six excitations at the "
        r"arm's compiled two-qubit cost, written $|\Delta E|$ @ 2Q. The "
        r"Krylov arm uses a seeded random sector kick overlapping every "
        r"target state, exact propagation, best-matching-root scoring, and "
        r"first-order-Trotter state-preparation costing --- every convention "
        r"favoring Krylov. Daggers mark arms that exhausted the pool without "
        r"meeting the residual stop.}"
    )
    lines.append(r"\begin{center}")
    lines.append(r"\scriptsize")
    lines.append(r"\begin{ruledtabular}")
    lines.append(r"\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}lccc@{}}")
    lines.append(
        r"Case & fixed class & real-time Krylov & selected $+$ exchange \\"
    )
    lines.append(r"\colrule")
    for case, record in matrix["cases"].items():
        fixed = record["fixed_linear_response"]
        krylov = (record["krylov"].get("best_per_cost_envelope") or [None])[-1]
        cells = [
            rf"{_sci(fixed['max_root_abs_error'])} @ {fixed['total_2q']:.0f}",
            (
                rf"{_sci(krylov['max_root_abs_error'])} @ {krylov['cum_2q']:.0f}"
                if krylov
                else "--"
            ),
        ]
        for key in ("selected_plus_exchange",):
            arm = record.get(key)
            if arm is None:
                cells.append("--")
                continue
            mark = r"$^\dagger$" if arm.get("stop_reason") == "pool_exhausted" else ""
            cells.append(
                rf"{_sci(arm['max_root_abs_error'])} @ {arm['total_2q']:.0f}{mark}"
            )
        lines.append(f"{_escape(case)} & " + " & ".join(cells) + r" \\")
    lines.append(r"\end{tabular*}")
    lines.append(r"\end{ruledtabular}")
    lines.append(r"\end{center}")
    lines.append(r"\end{widetext}")
    return "\n".join(lines) + "\n"


def build_driven_dynamics_fragment() -> str:
    payload = _load(DRIVEN_JSON)
    lines = [_fragment_header([DRIVEN_JSON])]
    lines.append(r"\begin{widetext}")
    lines.append(
        r"\inlinetablecaption{tab:qse_driven_diag}{Statevector-diagnostic "
        r"frozen-QSE driven propagation on the six Paper-I regimes: initial "
        r"state is the selected first-excitation Ritz root, driven by the "
        r"staggered-density gaussian-sinusoid pulse ($A=0.2$, $T=8$, 160 "
        r"midpoint steps) at the worst frequency of a QSE-anchored sweep. "
        r"The escape flux $\smash{[\Var_\Psi(H(t))-\|(\widehat M(t)-E)y\|^2]_+^{1/2}}$ "
        r"is measurement-compatible; its $t{=}0$ value is the static Ritz "
        r"residual and stays below the selection stop "
        r"$\varepsilon=10^{-3}$.}"
    )
    lines.append(r"\begin{center}")
    lines.append(r"\scriptsize")
    lines.append(r"\begin{ruledtabular}")
    lines.append(r"\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}lcccccc@{}}")
    lines.append(
        r"Regime & $k$ & $\omega^\ast$ & flux $t{=}0$ & max flux & "
        r"min $|\langle\Psi_{\rm ex}|\Psi\rangle|^2$ & exact response (ptp) \\"
    )
    lines.append(r"\colrule")
    for regime, record in payload["regimes"].items():
        worst = max(
            record["omega_sweep"], key=lambda row: float(row["summary"]["max_escape_flux"])
        )
        summary = worst["summary"]
        lines.append(
            rf"{_escape(regime)} & {record['selection']['support_size']} & "
            rf"{worst['omega']:.3f} & {_sci(summary['initial_escape_flux'])} & "
            rf"{_sci(summary['max_escape_flux'])} & {summary['min_fidelity']:.4f} & "
            rf"{_sci(summary['exact_density_peak_to_peak'])} \\"
        )
    lines.append(r"\end{tabular*}")
    lines.append(r"\end{ruledtabular}")
    lines.append(r"\end{center}")
    lines.append(r"\end{widetext}")
    return "\n".join(lines) + "\n"


def build_adaptive_dynamics_fragment() -> str:
    payload = _load(ADAPTIVE_JSON)
    lines = [_fragment_header([ADAPTIVE_JSON])]
    lines.append(
        r"\inlinetablecaption{tab:qse_adaptive_diag}{Frozen versus adaptive "
        r"QSE propagation at each regime's worst-escape drive frequency. "
        r"Adaptive growth admits, when the escape flux exceeds $10^{-2}$, "
        r"the pool record whose manifold-orthogonal component best aligns "
        r"with the unrepresented drift, then rebuilds the retained support "
        r"in place.}"
    )
    lines.append(r"\begin{center}")
    lines.append(r"\scriptsize")
    lines.append(r"\begin{ruledtabular}")
    lines.append(r"\begin{tabular}{lccccc}")
    lines.append(
        r"Regime & $\omega^\ast$ & min fid.\ (frozen) & min fid.\ (adaptive) & "
        r"records added & added 2Q \\"
    )
    lines.append(r"\colrule")
    for regime, record in payload["regimes"].items():
        frozen = record["arms"]["frozen"]["summary"]
        adaptive = record["arms"]["adaptive"]["summary"]
        lines.append(
            rf"{_escape(regime)} & {record['omega']:.3f} & "
            rf"{frozen['min_fidelity']:.4f} & {adaptive['min_fidelity']:.4f} & "
            rf"{adaptive['growth_event_count']} & "
            rf"{record['arms']['adaptive']['added_2q_total']:.0f} \\"
        )
    lines.append(r"\end{tabular}")
    lines.append(r"\end{ruledtabular}")
    lines.append(r"\end{center}")
    return "\n".join(lines) + "\n"



# Only the terms of the production three-term score are ablated; the Ritz
# window gain and the explicit conditioning penalty were evaluated and
# removed, so arms disabling them coincide with the anchor by construction.
_ABLATION_LABELS = {
    "full": "production score (anchor)",
    "no_novelty_weight": "no metric-novelty weight",
    "no_novelty_floor": "no metric-novelty floor",
    "no_residual": "no residual capture",
    "no_cost_discount": "no cost discount",
}
_ABLATION_ORDER = (
    "weak_weak",
    "intermediate_weak",
    "strong_weak_u8",
    "weak_strong",
    "intermediate_strong",
    "strong_strong_u8",
)


def build_ablation_fragment() -> str:
    payload = _load(ABLATION_JSON)
    variants = [k for k in _ABLATION_LABELS if any(
        k in rec["arms"] for rec in payload["regimes"].values())]
    lines = [_fragment_header([ABLATION_JSON])]
    lines.append(r"\begin{widetext}")
    lines.append(
        r"\inlinetablecaption{tab:qse_ablation_matrix}{Selection-score ablations "
        r"at the production residual stop $\varepsilon=10^{-3}$, so support size "
        r"$k$ is an output: a redundant term shows as equal accuracy at larger "
        r"$k$, and a load-bearing term as failure to converge "
        r"(\texttt{pool\_exhausted}). Entries are $k$ and the maximum error over "
        r"the lowest six excitations; daggers mark runs that exhausted the pool "
        r"without meeting the stop.}"
    )
    lines.append(r"\begin{center}")
    lines.append(r"\scriptsize")
    lines.append(r"\begin{ruledtabular}")
    lines.append(r"\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}l" + "c" * len(variants) + r"@{}}")
    lines.append("Regime & " + " & ".join(
        _ABLATION_LABELS[k].replace("no ", "no~") for k in variants) + r" \\")
    lines.append(r"\colrule")
    for regime, rec in payload["regimes"].items():
        cells = []
        for key in variants:
            arm = rec["arms"].get(key)
            if arm is None:
                cells.append("--")
                continue
            mark = r"$^\dagger$" if arm.get("stop_reason") == "pool_exhausted" else ""
            cells.append(rf"{arm['support_size']}{mark} / {_sci(arm['max_root_abs_error'])}")
        lines.append(_escape(regime) + " & " + " & ".join(cells) + r" \\")
    lines.append(r"\end{tabular*}")
    lines.append(r"\end{ruledtabular}")
    lines.append(r"\end{center}")
    lines.append(r"\end{widetext}")
    return "\n".join(lines) + "\n"



def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    args = parser.parse_args(argv)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    fragments = {
        "paper_iii_multiroot_table.tex": build_multiroot_fragment(),
        "paper_iii_comparator_table.tex": build_comparator_fragment(),
        "paper_iii_peierls_table.tex": build_peierls_fragment(),
        "paper_iii_comparator_matrix_table.tex": build_comparator_matrix_fragment(),
    }
    optional = {
        "paper_iii_driven_table.tex": (build_driven_dynamics_fragment, DRIVEN_JSON),
        "paper_iii_adaptive_table.tex": (build_adaptive_dynamics_fragment, ADAPTIVE_JSON),
        "paper_iii_ablation_table.tex": (build_ablation_fragment, ABLATION_JSON),
    }
    for name, (builder, source) in optional.items():
        if source.is_file():
            fragments[name] = builder()
        else:
            print(f"skipped {name}: missing {source}")
    for name, content in fragments.items():
        (args.output_dir / name).write_text(content, encoding="utf-8")
        print(f"wrote {args.output_dir / name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
