#!/usr/bin/env python3
"""Emit Paper III manuscript fragments from growth-trace campaign evidence.

Reporting convention (user, 2026-08-26): show the excitation gaps first, then
cost tables below, for the three methods plus the non-adaptive baseline. Every
cost cell carries all four axes -- N2q, D2q, Dc, and estimator queries -- per
the protocol's mandatory-reporting rule.

Methods, named as methods (never "arms"):
  ours                      -- cost-weighted geometric selection + certified exchange
  adaptive QSE (Davidson)   -- external benchmark, residual-synthesized directions
  real-time Krylov          -- external benchmark, different construction family
  standard QSE (fixed class)-- non-adaptive baseline, complete linear-response class

Deterministic and regenerable from the committed campaign JSON.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Sequence

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

DEFAULT_CAMPAIGN = (
    REPO_ROOT
    / "output/diagnostics/paper_iii_growth_trace_20260826_v1/growth_trace_nph1.json"
)
DEFAULT_OUTPUT_DIR = REPO_ROOT / "MATH/paper_details/generated"

METHODS = (
    ("ours__every_k", "ours"),
    ("adaptive_qse", "adaptive QSE"),
    ("krylov", "real-time Krylov"),
    ("fixed_class", "standard QSE"),
)


def _sci(value: Any) -> str:
    if value is None:
        return "--"
    mantissa, exponent = f"{float(value):.0e}".split("e")
    body = rf"10^{{{int(exponent)}}}" if mantissa in ("1", "1.0") else \
        rf"{mantissa}\times10^{{{int(exponent)}}}"
    return f"${body}$"


def _escape(text: Any) -> str:
    return str(text).replace("_", r"\_")


def _header(source: Path) -> str:
    return (
        "% AUTO-GENERATED by pipelines/reporting/build_paper_iii_growth_fragments.py\n"
        "% Do not edit by hand; rerun the generator after refreshing evidence.\n"
        f"% source: {source.relative_to(REPO_ROOT)}\n"
    )


def _gap_figure(payload: dict[str, Any], out_pdf: Path) -> None:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.lines import Line2D

    regimes = list(payload["regimes"])
    exact_max = max(
        float(r) - float(payload["regimes"][g]["reference_ground_energy"])
        for g in regimes
        for r in payload["regimes"][g]["reference_excitations"]
    )
    ylim = exact_max * 1.32
    style = {
        "ours__every_k": ("ours", "#2673b8", "o"),
        "adaptive_qse": ("adaptive QSE", "#2f8f4e", "^"),
        "krylov": ("real-time Krylov", "#8a5fc0", "d"),
        "fixed_class": ("standard QSE", "#c05020", "s"),
    }

    fig, ax = plt.subplots(figsize=(7.2, 3.6), constrained_layout=True)
    width, gap = 1.0, 0.65
    xticks: list[float] = []
    xlabels: list[str] = []
    offscale: list[tuple[float, float, str]] = []
    seen: set[str] = set()

    for slot, regime in enumerate(regimes):
        rec = payload["regimes"][regime]
        e0 = float(rec["reference_ground_energy"])
        refs = [float(x) for x in rec["reference_excitations"]]
        base = slot * (width + gap)
        offs = [base + width * (i / max(len(refs) - 1, 1)) for i in range(len(refs))]
        xticks.append(base + width / 2.0)
        xlabels.append(regime.replace("_", "-"))
        ax.plot(offs, [r - e0 for r in refs], "_", color="#222222", markersize=13,
                markeredgewidth=2.0,
                label="exact (reference)" if slot == 0 else None, zorder=1)
        for key, (label, color, marker) in style.items():
            arm = rec["arms"].get(key)
            if not arm:
                continue
            rows = [r for r in arm["trace"] if r.get("root_energies")]
            if not rows:
                rows = [r for r in arm["trace"] if r.get("max_root_abs_error") is not None]
            best = min(
                rows, key=lambda r: (r["max_root_abs_error"] is None,
                                     r["max_root_abs_error"] or 0.0), default=None,
            ) if rows else None
            energies = (best or {}).get("root_energies")
            if not energies:
                continue
            xs, ys = [], []
            for x, energy in zip(offs, energies):
                g = float(energy) - e0
                if g > ylim:
                    offscale.append((x, g, color))
                else:
                    xs.append(x)
                    ys.append(g)
            ax.plot(xs, ys, marker, color=color, markersize=5, markerfacecolor="none",
                    markeredgewidth=1.3,
                    label=label if key not in seen else None, zorder=2)
            seen.add(key)

    for x, value, color in offscale:
        ax.plot([x], [ylim * 0.97], marker="^", color=color, markersize=6, zorder=3)
        ax.annotate(f"{value:.1f}", (x, ylim * 0.97), textcoords="offset points",
                    xytext=(0, -10), ha="center", fontsize=6, color=color)

    ax.set_ylim(0.0, ylim)
    ax.set_xticks(xticks)
    ax.set_xticklabels(xlabels, fontsize=7, rotation=18, ha="right")
    ax.set_ylabel(r"excitation gap $\omega_\nu = E_\nu - E_0$", fontsize=9)
    ax.tick_params(axis="y", labelsize=8)
    ax.grid(True, axis="y", alpha=0.25, linewidth=0.5)
    handles, labels = ax.get_legend_handles_labels()
    if offscale:
        handles.append(Line2D([], [], marker="^", color="#c05020", linestyle="none",
                              markersize=6))
        labels.append("off scale (value shown)")
    ax.legend(handles, labels, fontsize=7, loc="upper left", framealpha=0.95, ncol=3)
    out_pdf.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_pdf)
    fig.savefig(out_pdf.with_suffix(".png"), dpi=200)
    plt.close(fig)


def _cost_cell(entry: dict[str, Any] | None) -> str:
    if not entry or entry.get("status") != "REACHED":
        terminal = (entry or {}).get("terminal") or {}
        err = terminal.get("max_root_abs_error")
        tag = "unatt." if (entry or {}).get("status", "").startswith("UNATT") else "n.r."
        return rf"\textit{{{tag}}}" + (rf"\,{_sci(err)}" if err is not None else "")
    x = entry["crossing"]
    est = x.get("estimator") or {}
    q = est.get("queries")
    return (
        rf"{x['n2q']:.0f}/{x['d2q']:.0f}/{x['dc']:.0f}"
        + (rf" \,[{q}]" if q is not None else "")
    )


def build_cost_tables(payload: dict[str, Any], source: Path, *, suffix: str = "") -> str:
    tier = {'nph1': 'Cutoff $n_{\\rm ph}=1$.', 'nph3': 'Cutoff $n_{\\rm ph}=3$.'}.get(str(payload.get('regime_set', '')), '')
    targets = sorted(
        {e for rec in payload["regimes"].values() for e in rec["cells"]},
        key=lambda x: -float(x),
    )
    lines = [_header(source)]
    # Targets whose cells are identical are emitted once: at a given tier the
    # crossing subspace often satisfies several targets, and repeating the same
    # numbers under three captions is noise, not evidence.
    signature: dict[str, list[str]] = {}
    for eps in targets:
        key = "|".join(
            _cost_cell(rec["cells"].get(eps, {}).get(k))
            for rec in payload["regimes"].values()
            for k, _l in METHODS
        )
        signature.setdefault(key, []).append(eps)
    groups = list(signature.values())
    for group in groups:
        eps = group[0]
        lines.append(r"\begin{widetext}")
        lines.append(
            rf"\inlinetablecaption{{tab:qse_growth{suffix}_{eps.replace('-', 'm').replace('.', '')}}}"
            rf"{{{tier} Resources required to resolve the lowest six excitations to "
            rf"{'$\\varepsilon_E=' + _sci(float(eps))[1:-1] + '$' if len(group) == 1 else 'each of $\\varepsilon_E \\in \\{' + ', '.join(_sci(float(e))[1:-1] for e in group) + '\\}$ (the certified subspace is the same for all of them)'}, on an identical record alphabet with "
            r"every method grown one record at a time (no method's stopping rule enters the "
            r"comparison). Cells give the deterministic graph-span proxy $N_{2q}/D_{2q}/D_c$ "
            r"and, in brackets, the matrix-measurement estimator queries. "
            r"\textit{unatt.}\ marks a manifold that cannot reach the target at any budget; "
            r"\textit{n.r.}\ marks a method that did not reach it within its dimension cap, "
            r"terminal error shown.}"
        )
        lines.append(r"\begin{center}")
        lines.append(r"\scriptsize")
        lines.append(r"\begin{ruledtabular}")
        lines.append(r"\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}l" + "c" * len(METHODS) + r"@{}}")
        lines.append("Regime & " + " & ".join(label for _k, label in METHODS) + r" \\")
        lines.append(r"\colrule")
        for regime, rec in payload["regimes"].items():
            row = rec["cells"].get(eps, {})
            cells = [_cost_cell(row.get(key)) for key, _label in METHODS]
            lines.append(_escape(regime) + " & " + " & ".join(cells) + r" \\")
        lines.append(r"\end{tabular*}")
        lines.append(r"\end{ruledtabular}")
        lines.append(r"\end{center}")
        lines.append(r"\end{widetext}")
    return "\n".join(lines) + "\n"


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--campaign-json", type=Path, default=DEFAULT_CAMPAIGN)
    parser.add_argument("--suffix", default="", help="Tag appended to fragment filenames, e.g. _nph3.")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    args = parser.parse_args(argv)

    campaign = Path(args.campaign_json).resolve()
    payload = json.loads(campaign.read_text(encoding="utf-8"))
    out = Path(args.output_dir)
    out.mkdir(parents=True, exist_ok=True)
    sfx = str(args.suffix)
    _gap_figure(payload, out / f"paper_iii_growth_gaps{sfx}.pdf")
    (out / f"paper_iii_growth_cost_tables{sfx}.tex").write_text(
        build_cost_tables(payload, campaign, suffix=sfx), encoding="utf-8"
    )
    print(f"wrote {out / f'paper_iii_growth_gaps{sfx}.pdf'}")
    print(f"wrote {out / f'paper_iii_growth_cost_tables{sfx}.tex'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
