#!/usr/bin/env python3
"""Uniform round-50 Qiskit compilation for Paper-I insertion overlays.

The historical overlay inputs were generated by more than one reporting
adapter.  Some adapters compiled Pauli labels in serialized/native order,
whereas the runtime parameterization and the current Paper-I compiler use
coefficient-bearing generators in deterministic runtime order.  This module
normalizes every RA endpoint through the current execution-aware compiler and
validates saved Append endpoints against the same compiler fingerprint.
"""

from __future__ import annotations

import gzip
import hashlib
import json
import math
from pathlib import Path
import tarfile
from typing import Any, Mapping, Sequence

import numpy as np

from pipelines.exact_bench.paper_i_hh_recovery_prefix_qiskit_sidecar import (
    derive_execution_order_repaired_checkpoint,
    reconstruct_reference_state,
    validate_active_prefix_checkpoint,
)
from pipelines.exact_bench.table_i_qiskit_resource_compile import (
    TABLE_I_COMPILED_BASIS_GATES,
    TABLE_I_GROUPED_EXACT_SYNTHESIS_ID,
    TABLE_I_QISKIT_BASIS_WORK_SCHEMA,
    TABLE_I_QISKIT_COMPILE_CONVENTION,
    TABLE_I_STRUCTURAL_ANGLE_CONVENTION,
    TableIQiskitCompileConfig,
    compile_table_i_ansatz_terms,
)
from pipelines.reporting.paper_i_qiskit_cost_tuple import qiskit_cost_fields
from src.quantum.pauli_polynomial_class import PauliPolynomial
from src.quantum.qubitization_module import PauliTerm
from src.quantum.vqe_latex_python_pairs import AnsatzTerm


UNIFORM_K50_SCHEMA = "paper_i_hh_uniform_k50_qiskit_costs_v1"
COMPILER_FINGERPRINT_SCHEMA = "paper_i_qiskit_compiler_fingerprint_v1"
TERMINAL_ITERATION = 50
QISKIT_FIELDS = ("N2q", "D2q", "Dc", "W1q")
RESOURCE_FIELDS = (*QISKIT_FIELDS, "S_alg")
POLICY_ORDER = ("always", "plateau", "no_insertion", "append")


def _sha256_path(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _canonical_sha256(payload: Any) -> str:
    encoded = json.dumps(
        payload,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def _mapping(value: Any, *, label: str) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise TypeError(f"{label}: expected a mapping")
    return value


def _sequence(value: Any, *, label: str) -> Sequence[Any]:
    if not isinstance(value, Sequence) or isinstance(
        value, (str, bytes, bytearray)
    ):
        raise TypeError(f"{label}: expected a sequence")
    return value


def _finite_float(value: Any, *, label: str) -> float:
    out = float(value)
    if not math.isfinite(out):
        raise ValueError(f"{label}: expected a finite number")
    return out


def _positive_integer(value: Any, *, label: str) -> int:
    if isinstance(value, bool):
        raise TypeError(f"{label}: expected a positive integer")
    out = int(value)
    if out <= 0 or out != value:
        raise ValueError(f"{label}: expected a positive integer")
    return out


def _repo_path(repo_root: Path, raw: Any, *, label: str) -> Path:
    relative = Path(str(raw))
    if relative.is_absolute() or ".." in relative.parts:
        raise ValueError(f"{label}: unsafe repository-relative path")
    path = repo_root / relative
    if not path.is_file():
        raise FileNotFoundError(f"{label}: {path}")
    return path


def _locked_config() -> TableIQiskitCompileConfig:
    return TableIQiskitCompileConfig(
        basis_gates=TABLE_I_COMPILED_BASIS_GATES,
        optimization_level=0,
        seed_transpiler=7,
        structure_theta_value=1.0,
        include_reference_state=True,
        compile_convention=TABLE_I_QISKIT_COMPILE_CONVENTION,
        coefficient_tolerance=1.0e-12,
        grouped_exact_max_active_qubits=5,
    )


def compiler_fingerprint(payload: Mapping[str, Any]) -> dict[str, Any]:
    """Validate and project the complete common compiler-settings identity."""

    required_equalities = {
        "compiled_circuit_stats_status": "ok",
        "compiled_resource_qiskit_validated": True,
        "compile_convention": TABLE_I_QISKIT_COMPILE_CONVENTION,
        "angle_convention": TABLE_I_STRUCTURAL_ANGLE_CONVENTION,
        "compiled_circuit_scope": (
            "ansatz_circuit_including_reference_state"
        ),
        "qiskit_transpile_optimization_level": 0,
        "qiskit_transpile_seed": 7,
        "grouped_exact_coefficient_tolerance": 1.0e-12,
        "grouped_exact_max_active_qubits": 5,
        "grouped_exact_synthesis_id": TABLE_I_GROUPED_EXACT_SYNTHESIS_ID,
        "qiskit_basis_work_status": "ok",
        "qiskit_basis_work_schema": TABLE_I_QISKIT_BASIS_WORK_SCHEMA,
        "qiskit_basis_work_non_attributable_operator_count": 0,
    }
    for key, expected in required_equalities.items():
        if payload.get(key) != expected:
            raise ValueError(
                "Paper-I compiler fingerprint drifted: "
                f"{key}={payload.get(key)!r}, expected={expected!r}"
            )
    if tuple(payload.get("compiled_basis_gates", ())) != (
        TABLE_I_COMPILED_BASIS_GATES
    ):
        raise ValueError("Paper-I compiled basis-gate fingerprint drifted")
    qiskit_version = str(payload.get("qiskit_version") or "").strip()
    if not qiskit_version:
        raise ValueError("Paper-I compiler fingerprint lacks qiskit_version")

    return {
        "schema": COMPILER_FINGERPRINT_SCHEMA,
        "compiler_entrypoint": (
            "pipelines.exact_bench.table_i_qiskit_resource_compile."
            "compile_table_i_ansatz_terms"
        ),
        "input_semantics": (
            "coefficient-bearing execution-aware AnsatzTerm sequence"
        ),
        "compile_convention": TABLE_I_QISKIT_COMPILE_CONVENTION,
        "qiskit_version": qiskit_version,
        "basis_gates": list(TABLE_I_COMPILED_BASIS_GATES),
        "optimization_level": 0,
        "seed_transpiler": 7,
        "angle_convention": TABLE_I_STRUCTURAL_ANGLE_CONVENTION,
        "structure_theta_value": 1.0,
        "circuit_scope": "ansatz_circuit_including_reference_state",
        "coefficient_tolerance": 1.0e-12,
        "grouped_exact_max_active_qubits": 5,
        "grouped_exact_synthesis_id": TABLE_I_GROUPED_EXACT_SYNTHESIS_ID,
        "qiskit_basis_work_schema": TABLE_I_QISKIT_BASIS_WORK_SCHEMA,
        "term_order_contract": (
            "combine equal Pauli labels, discard identity/tolerance-zero "
            "terms, then lexicographically sort coefficient-bearing labels "
            "inside each logical generator"
        ),
        "topology": {
            "backend": None,
            "coupling_map": None,
            "initial_layout": None,
            "layout_method": None,
            "routing_method": None,
        },
    }


def compiler_fingerprint_sha256(
    fingerprint: Mapping[str, Any],
) -> str:
    if fingerprint.get("schema") != COMPILER_FINGERPRINT_SCHEMA:
        raise ValueError("unsupported Paper-I compiler fingerprint schema")
    return _canonical_sha256(fingerprint)


def _normalized_term(raw: Mapping[str, Any], *, label: str) -> dict[str, Any]:
    pauli = str(raw.get("pauli_exyz") or "").strip().lower()
    if not pauli:
        raise ValueError(f"{label}: missing Pauli label")
    nq = int(raw.get("nq", len(pauli)))
    if len(pauli) != nq:
        raise ValueError(
            f"{label}: Pauli width {len(pauli)} disagrees with nq={nq}"
        )
    coeff_re = _finite_float(raw.get("coeff_re", 0.0), label=f"{label} real")
    coeff_im = _finite_float(raw.get("coeff_im", 0.0), label=f"{label} imag")
    return {
        "pauli_exyz": pauli,
        "coeff_re": coeff_re,
        "coeff_im": coeff_im,
        "nq": nq,
    }


def _ops_from_operator_rows(
    operator_rows: Sequence[Any],
    *,
    label: str,
    sort_terms: bool,
) -> tuple[tuple[AnsatzTerm, ...], int, dict[str, Any]]:
    if len(operator_rows) != TERMINAL_ITERATION:
        raise ValueError(
            f"{label}: expected {TERMINAL_ITERATION} terminal operators, "
            f"observed {len(operator_rows)}"
        )
    ops: list[AnsatzTerm] = []
    widths: set[int] = set()
    reordered_indices: list[int] = []
    for operator_index, raw_operator in enumerate(operator_rows):
        operator = _mapping(
            raw_operator, label=f"{label} operator {operator_index}"
        )
        operator_label = str(operator.get("label") or "").strip()
        if not operator_label:
            raise ValueError(
                f"{label} operator {operator_index}: missing generator label"
            )
        raw_terms = _sequence(
            operator.get("serialized_terms_exyz_in_execution_order"),
            label=f"{label} operator {operator_index} terms",
        )
        terms = [
            _normalized_term(
                _mapping(
                    raw_term,
                    label=f"{label} operator {operator_index} term",
                ),
                label=f"{label} operator {operator_index} term",
            )
            for raw_term in raw_terms
        ]
        if not terms:
            raise ValueError(f"{label} operator {operator_index}: no terms")
        if sort_terms:
            sorted_terms = sorted(terms, key=lambda row: row["pauli_exyz"])
            if terms != sorted_terms:
                reordered_indices.append(operator_index)
            terms = sorted_terms
        polynomial = PauliPolynomial("JW")
        for term in terms:
            widths.add(int(term["nq"]))
            polynomial.add_term(
                PauliTerm(
                    int(term["nq"]),
                    ps=str(term["pauli_exyz"]),
                    pc=complex(term["coeff_re"], term["coeff_im"]),
                )
            )
        ops.append(
            AnsatzTerm(
                label=operator_label,
                polynomial=polynomial,
                execution_mode=str(
                    operator.get("execution_mode") or "termwise_product"
                ),
            )
        )
    if len(widths) != 1:
        raise ValueError(f"{label}: inconsistent Pauli widths {sorted(widths)}")
    return (
        tuple(ops),
        int(next(iter(widths))),
        {
            "authority": (
                "deterministic runtime parameterization order "
                "(lexicographic Pauli label)"
                if sort_terms
                else "checkpoint.parameterization.blocks[].runtime_terms_exyz"
            ),
            "reordered_operator_count": len(reordered_indices),
            "reordered_operator_indices": reordered_indices,
            "substantive_term_changes": False,
        },
    )


def _ops_from_validated_checkpoint(
    validated: Any,
) -> tuple[AnsatzTerm, ...]:
    ops: list[AnsatzTerm] = []
    for block in validated.layout.blocks:
        polynomial = PauliPolynomial("JW")
        for term in block.terms:
            polynomial.add_term(
                PauliTerm(
                    int(term.nq),
                    ps=str(term.pauli_exyz).lower(),
                    pc=complex(float(term.coeff_real), 0.0),
                )
            )
        ops.append(
            AnsatzTerm(
                label=str(block.candidate_label),
                polynomial=polynomial,
                execution_mode=str(block.execution_mode),
            )
        )
    return tuple(ops)


def _compile_ops(
    *,
    ops: Sequence[AnsatzTerm],
    num_qubits: int,
    source_payload: Mapping[str, Any],
    source_kind: str,
    s_alg: int,
) -> dict[str, Any]:
    reference_state, reference_receipt = reconstruct_reference_state(
        source_payload,
        num_qubits=num_qubits,
    )
    compiled = compile_table_i_ansatz_terms(
        ops=tuple(ops),
        num_qubits=num_qubits,
        reference_state=np.asarray(reference_state, dtype=complex),
        source_kind=source_kind,
        config=_locked_config(),
    )
    fingerprint = compiler_fingerprint(compiled)
    qiskit = qiskit_cost_fields(compiled)
    costs = {
        field: _positive_integer(qiskit[field], label=f"{source_kind} {field}")
        for field in QISKIT_FIELDS
    }
    costs["S_alg"] = _positive_integer(s_alg, label=f"{source_kind} S_alg")
    return {
        "costs": costs,
        "B1q": _positive_integer(qiskit["B1q"], label=f"{source_kind} B1q"),
        "compiler_fingerprint": fingerprint,
        "compiler_fingerprint_sha256": compiler_fingerprint_sha256(
            fingerprint
        ),
        "compile_receipt": {
            "status": "recompiled_from_coefficient_bearing_terminal_prefix",
            "num_qubits": int(compiled["num_qubits"]),
            "logical_operator_count": int(compiled["logical_operator_count"]),
            "runtime_rotation_count": int(compiled["runtime_rotation_count"]),
            "generator_coefficients_sha256": str(
                compiled["generator_coefficients_sha256"]
            ),
            "reference_state": reference_receipt,
        },
    }


def compile_compact_always_endpoint(
    row: Mapping[str, Any],
    *,
    repo_root: Path,
) -> dict[str, Any]:
    """Compile one compact always-insertion terminal prefix at round 50."""

    regime = str(row.get("regime") or "")
    source = _mapping(row.get("source"), label=f"{regime} always source")
    compact_path = _repo_path(
        repo_root,
        source.get("compact_evidence"),
        label=f"{regime} compact always evidence",
    )
    observed_sha = _sha256_path(compact_path)
    expected_sha = str(source.get("compact_evidence_sha256") or "")
    if observed_sha != expected_sha:
        raise ValueError(f"{regime}: compact always evidence SHA-256 drifted")
    with gzip.open(compact_path, "rt", encoding="utf-8") as handle:
        compact = json.load(handle)
    compact = _mapping(compact, label=f"{regime} compact always root")
    if compact.get("schema") != (
        "paper_i_hh_insertion_compact_transfer_evidence_v1"
    ):
        raise ValueError(f"{regime}: compact always schema drifted")
    payload = _mapping(
        compact.get("payload"), label=f"{regime} compact always payload"
    )
    if _canonical_sha256(payload) != compact.get("payload_sha256"):
        raise ValueError(f"{regime}: compact always payload SHA-256 drifted")
    compact_source = _mapping(
        compact.get("source"), label=f"{regime} compact source receipt"
    )
    if (
        compact_source.get("archive_sha256") != source.get("archive_sha256")
        or compact_source.get("member") != source.get("member")
    ):
        raise ValueError(f"{regime}: compact/source archive binding drifted")
    adapt = _mapping(payload.get("adapt_vqe"), label=f"{regime} adapt_vqe")
    history = _sequence(adapt.get("history"), label=f"{regime} history")
    terminal = _mapping(history[-1], label=f"{regime} terminal history row")
    operator_rows = _sequence(
        terminal.get("_ordered_active_operators"),
        label=f"{regime} compact terminal operators",
    )
    ops, num_qubits, order_receipt = _ops_from_operator_rows(
        operator_rows,
        label=f"{regime} compact always",
        sort_terms=True,
    )
    result = _compile_ops(
        ops=ops,
        num_qubits=num_qubits,
        source_payload=payload,
        source_kind="paper_i_overlay_ra_always_k50_uniform_recompile",
        s_alg=_mapping(
            row.get("terminal_costs"),
            label=f"{regime} always terminal costs",
        )["S_alg"],
    )
    result["compile_receipt"].update(
        {
            "terminal_iteration": TERMINAL_ITERATION,
            "term_order": order_receipt,
            "source_payload_sha256": str(compact["payload_sha256"]),
        }
    )
    result["source"] = {
        "mode": "validated_compact_transfer_evidence",
        "path": str(compact_path.relative_to(repo_root)),
        "sha256": observed_sha,
        "source_archive_sha256": str(source["archive_sha256"]),
        "source_member": str(source["member"]),
    }
    return result


def _read_tar_json_member(path: Path, *, member_name: str) -> dict[str, Any]:
    """Read one early tar member without indexing the rest of a large archive."""

    try:
        with tarfile.open(path, mode="r|gz") as archive:
            for member in archive:
                if member.name != member_name:
                    continue
                if not member.isfile():
                    raise ValueError(f"{path}: {member_name} is not a file")
                handle = archive.extractfile(member)
                if handle is None:
                    raise ValueError(f"{path}: cannot read {member_name}")
                payload = json.load(handle)
                if not isinstance(payload, dict):
                    raise TypeError(f"{path}: {member_name} is not an object")
                return payload
    except tarfile.TarError as exc:
        raise ValueError(f"{path}: invalid tar archive: {exc}") from exc
    raise ValueError(f"{path}: missing {member_name}")


def _terminal_checkpoint(payload: Mapping[str, Any]) -> Mapping[str, Any]:
    adapt = _mapping(payload.get("adapt_vqe"), label="adapt_vqe")
    candidates: list[Mapping[str, Any]] = []
    # Prefer the explicit terminal checkpoint.  A result may also retain the
    # round-50 post-admission checkpoint in history; its signed parameters can
    # differ after the final refit even when the structural prefix is the same.
    for raw in (
        adapt.get("terminal_active_prefix_checkpoint"),
        payload.get("terminal_active_prefix_checkpoint"),
    ):
        if isinstance(raw, Mapping):
            candidates.append(raw)
    history = adapt.get("history")
    if isinstance(history, Sequence) and not isinstance(
        history, (str, bytes, bytearray)
    ) and history:
        terminal = history[-1]
        if isinstance(terminal, Mapping) and isinstance(
            terminal.get("active_prefix_checkpoint"), Mapping
        ):
            candidates.append(terminal["active_prefix_checkpoint"])
    matches = [
        row
        for row in candidates
        if row.get("schema") == "paper_i_signed_active_prefix_checkpoint_v1"
        and int(row.get("outer_iteration", -1)) == TERMINAL_ITERATION
    ]
    if not matches:
        raise ValueError("source result lacks a round-50 active-prefix checkpoint")
    if not str(matches[0].get("checkpoint_sha256") or ""):
        raise ValueError("round-50 active-prefix checkpoint lacks SHA-256")
    return matches[0]


def compile_checkpoint_archive_endpoint(
    row: Mapping[str, Any],
    *,
    repo_root: Path,
    policy: str,
) -> dict[str, Any]:
    """Compile one plateau/no-insertion endpoint from its signed checkpoint."""

    if policy not in {"plateau", "no_insertion"}:
        raise ValueError(f"unsupported checkpoint policy: {policy}")
    regime = str(row.get("regime") or "")
    source = _mapping(row.get("source"), label=f"{regime} {policy} source")
    archive_key = "archive" if policy == "plateau" else "path"
    sha_key = "archive_sha256" if policy == "plateau" else "sha256"
    archive_path = _repo_path(
        repo_root,
        source.get(archive_key),
        label=f"{regime} {policy} archive",
    )
    observed_archive_sha = _sha256_path(archive_path)
    if observed_archive_sha != source.get(sha_key):
        raise ValueError(f"{regime}: {policy} archive SHA-256 drifted")
    member_name = str(source.get("member") or "")
    if not member_name or member_name.startswith("/") or ".." in Path(
        member_name
    ).parts:
        raise ValueError(f"{regime}: unsafe {policy} archive member")
    payload = _read_tar_json_member(archive_path, member_name=member_name)
    checkpoint = _terminal_checkpoint(payload)
    repaired, repair_receipt = derive_execution_order_repaired_checkpoint(
        checkpoint,
        expected_outer_iteration=TERMINAL_ITERATION,
    )
    validated = validate_active_prefix_checkpoint(
        repaired,
        expected_outer_iteration=TERMINAL_ITERATION,
    )
    if int(validated.layout.logical_parameter_count) != TERMINAL_ITERATION:
        raise ValueError(f"{regime}: {policy} active depth is not 50")
    result = _compile_ops(
        ops=_ops_from_validated_checkpoint(validated),
        num_qubits=int(validated.num_qubits),
        source_payload=payload,
        source_kind=f"paper_i_overlay_ra_{policy}_k50_uniform_recompile",
        s_alg=_mapping(
            row.get("terminal_costs"),
            label=f"{regime} {policy} terminal costs",
        )["S_alg"],
    )
    result["compile_receipt"].update(
        {
            "terminal_iteration": TERMINAL_ITERATION,
            "checkpoint_sha256": str(validated.checkpoint_sha256),
            "term_order": repair_receipt,
        }
    )
    result["source"] = {
        "mode": "hash_locked_transfer_archive_terminal_checkpoint",
        "path": str(archive_path.relative_to(repo_root)),
        "sha256": observed_archive_sha,
        "member": member_name,
    }
    return result


def saved_append_endpoint(
    cell: Mapping[str, Any],
) -> dict[str, Any]:
    """Validate one saved Append compile payload against the common contract."""

    fingerprint = _mapping(
        cell.get("compiler_fingerprint"),
        label="Append compiler fingerprint",
    )
    fingerprint = dict(fingerprint)
    digest = compiler_fingerprint_sha256(fingerprint)
    if digest != cell.get("compiler_fingerprint_sha256"):
        raise ValueError("Append compiler fingerprint SHA-256 drifted")
    costs_raw = _mapping(cell.get("terminal_costs"), label="Append costs")
    costs = {
        field: _positive_integer(costs_raw.get(field), label=f"Append {field}")
        for field in RESOURCE_FIELDS
    }
    compile_receipt = _mapping(
        cell.get("compile_receipt"), label="Append compile receipt"
    )
    if int(compile_receipt.get("logical_operator_count", -1)) != (
        TERMINAL_ITERATION
    ):
        raise ValueError("Append terminal compile is not the round-50 prefix")
    return {
        "costs": costs,
        "B1q": _positive_integer(
            compile_receipt.get("B1q"), label="Append B1q"
        ),
        "compiler_fingerprint": fingerprint,
        "compiler_fingerprint_sha256": digest,
        "compile_receipt": {
            **dict(compile_receipt),
            "status": "validated_saved_execution_aware_terminal_compile",
            "terminal_iteration": TERMINAL_ITERATION,
        },
        "source": dict(
            _mapping(cell.get("source"), label="Append source receipt")
        ),
    }


def _legacy_costs(row: Mapping[str, Any]) -> dict[str, int]:
    costs = _mapping(row.get("terminal_costs"), label="legacy terminal costs")
    return {
        field: _positive_integer(costs.get(field), label=f"legacy {field}")
        for field in RESOURCE_FIELDS
    }


def build_uniform_k50_dataset(
    *,
    repo_root: Path,
    plot_order: Sequence[str],
    source_rows: Mapping[
        str, Mapping[str, Mapping[str, Mapping[str, Any]]]
    ],
    append_cells: Mapping[str, Mapping[str, Mapping[str, Any]]],
) -> dict[str, Any]:
    """Build all 48 endpoint rows and fail on any compiler mismatch."""

    common_fingerprint: dict[str, Any] | None = None
    common_digest: str | None = None
    rows: list[dict[str, Any]] = []
    for kind in ("macro", "singleton"):
        kind_sources = _mapping(
            source_rows.get(kind), label=f"{kind} source rows"
        )
        append_by_regime = _mapping(
            append_cells.get(kind), label=f"{kind} Append cells"
        )
        for regime in plot_order:
            for policy in POLICY_ORDER:
                if policy == "append":
                    compiled = saved_append_endpoint(
                        _mapping(
                            append_by_regime.get(regime),
                            label=f"{kind}/{regime} Append cell",
                        )
                    )
                    legacy = dict(compiled["costs"])
                else:
                    policy_rows = _mapping(
                        kind_sources.get(policy),
                        label=f"{kind}/{policy} rows",
                    )
                    source_row = _mapping(
                        policy_rows.get(regime),
                        label=f"{kind}/{policy}/{regime} row",
                    )
                    legacy = _legacy_costs(source_row)
                    if policy == "always":
                        compiled = compile_compact_always_endpoint(
                            source_row,
                            repo_root=repo_root,
                        )
                    else:
                        compiled = compile_checkpoint_archive_endpoint(
                            source_row,
                            repo_root=repo_root,
                            policy=policy,
                        )
                fingerprint = dict(compiled["compiler_fingerprint"])
                digest = str(compiled["compiler_fingerprint_sha256"])
                if common_fingerprint is None:
                    common_fingerprint = fingerprint
                    common_digest = digest
                elif (
                    fingerprint != common_fingerprint
                    or digest != common_digest
                ):
                    raise ValueError(
                        "mixed Qiskit compiler fingerprints at "
                        f"{kind}/{regime}/{policy}"
                    )
                uniform_costs = dict(compiled["costs"])
                rows.append(
                    {
                        "representation_kind": kind,
                        "regime": str(regime),
                        "policy": policy,
                        "terminal_iteration": TERMINAL_ITERATION,
                        "costs": uniform_costs,
                        "B1q": int(compiled["B1q"]),
                        "legacy_reported_costs": legacy,
                        "uniform_minus_legacy": {
                            field: int(uniform_costs[field] - legacy[field])
                            for field in RESOURCE_FIELDS
                        },
                        "compiler_fingerprint_sha256": digest,
                        "compile_receipt": dict(
                            compiled["compile_receipt"]
                        ),
                        "source": dict(compiled["source"]),
                    }
                )
    expected_count = 2 * len(tuple(plot_order)) * len(POLICY_ORDER)
    if len(rows) != expected_count or common_fingerprint is None:
        raise ValueError(
            f"uniform Qiskit endpoint coverage is {len(rows)}/{expected_count}"
        )
    return {
        "schema": UNIFORM_K50_SCHEMA,
        "purpose": (
            "Use one execution-aware, backend-free Qiskit transpilation "
            "contract for every plotted Paper-I round-50 endpoint."
        ),
        "terminal_iteration": TERMINAL_ITERATION,
        "resource_tuple": list(RESOURCE_FIELDS),
        "endpoint_count": len(rows),
        "compiler_fingerprint": common_fingerprint,
        "compiler_fingerprint_sha256": common_digest,
        "fingerprint_guard": {
            "status": "all_endpoints_identical",
            "validated_endpoint_count": len(rows),
        },
        "rows": rows,
    }


def validate_uniform_k50_dataset(
    dataset: Mapping[str, Any],
    *,
    plot_order: Sequence[str],
) -> dict[tuple[str, str, str], Mapping[str, Any]]:
    """Validate a generated uniform dataset and index its endpoint rows."""

    if (
        dataset.get("schema") != UNIFORM_K50_SCHEMA
        or dataset.get("terminal_iteration") != TERMINAL_ITERATION
        or tuple(dataset.get("resource_tuple", ())) != RESOURCE_FIELDS
    ):
        raise ValueError("uniform round-50 Qiskit dataset contract drifted")
    fingerprint = _mapping(
        dataset.get("compiler_fingerprint"),
        label="uniform compiler fingerprint",
    )
    digest = compiler_fingerprint_sha256(fingerprint)
    if digest != dataset.get("compiler_fingerprint_sha256"):
        raise ValueError("uniform compiler fingerprint SHA-256 drifted")
    rows = _sequence(dataset.get("rows"), label="uniform endpoint rows")
    index: dict[tuple[str, str, str], Mapping[str, Any]] = {}
    for raw_row in rows:
        row = _mapping(raw_row, label="uniform endpoint row")
        key = (
            str(row.get("representation_kind")),
            str(row.get("regime")),
            str(row.get("policy")),
        )
        if (
            key in index
            or key[0] not in {"macro", "singleton"}
            or key[1] not in set(plot_order)
            or key[2] not in POLICY_ORDER
            or row.get("terminal_iteration") != TERMINAL_ITERATION
            or row.get("compiler_fingerprint_sha256") != digest
        ):
            raise ValueError(f"invalid or duplicate uniform endpoint row {key}")
        costs = _mapping(row.get("costs"), label=f"{key} costs")
        for field in RESOURCE_FIELDS:
            _positive_integer(costs.get(field), label=f"{key} {field}")
        index[key] = row
    expected = {
        (kind, str(regime), policy)
        for kind in ("macro", "singleton")
        for regime in plot_order
        for policy in POLICY_ORDER
    }
    if set(index) != expected or dataset.get("endpoint_count") != len(expected):
        raise ValueError("uniform round-50 Qiskit endpoint coverage drifted")
    guard = _mapping(
        dataset.get("fingerprint_guard"), label="uniform fingerprint guard"
    )
    if (
        guard.get("status") != "all_endpoints_identical"
        or guard.get("validated_endpoint_count") != len(expected)
    ):
        raise ValueError("uniform compiler fingerprint guard drifted")
    return index


__all__ = [
    "COMPILER_FINGERPRINT_SCHEMA",
    "POLICY_ORDER",
    "RESOURCE_FIELDS",
    "TERMINAL_ITERATION",
    "UNIFORM_K50_SCHEMA",
    "build_uniform_k50_dataset",
    "compile_checkpoint_archive_endpoint",
    "compile_compact_always_endpoint",
    "compiler_fingerprint",
    "compiler_fingerprint_sha256",
    "saved_append_endpoint",
    "validate_uniform_k50_dataset",
]
