"""Exact-wavefunction sensitivity diagnostic for the driven Holstein dimer.

The exact truncated Hamiltonian generates a unitary linear flow.  This module
therefore keeps full-state sensitivity and sensitivity of the contracted
31-coordinate moment representation separate.  Nearby wavefunctions are
propagated under the same Hamiltonian without trajectory renormalization; any
variation of their 31-coordinate distance is a contraction effect, while
their fidelity should remain constant up to integration error.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
from scipy.integrate import solve_ivp

from .cone_correction import closed_state_lifted_frobenius_norm
from .exact_reference import (
    _build_exact_dimer_model,
    _contract_matrix_state,
    _ground_state,
)
from .hubbard_dimer import DimerParameters, FloatArray
from .initial_condition_sensitivity import physicality_diagnostics
from .matrix_reference import matrix_state_to_closed_scalar_coordinates

ComplexArray = np.ndarray

DIRECTION_NAMES = ("drive", "relative_phonon_position")


@dataclass(frozen=True)
class ExactReferenceSensitivity:
    """Nearby exact states and their contracted moment separations."""

    times: FloatArray
    direction_names: tuple[str, ...]
    perturbation_amplitudes: FloatArray
    base_coordinates: FloatArray
    shadow_coordinates: FloatArray
    coordinate_euclidean_distances: FloatArray
    coordinate_frobenius_distances: FloatArray
    state_fidelities: FloatArray
    state_chord_distances: FloatArray
    raw_shadow_norms: FloatArray
    basis_norms: FloatArray
    base_tangent_overlaps: ComplexArray
    base_margins: FloatArray
    shadow_margins: FloatArray
    base_trace_residuals: FloatArray
    shadow_trace_residuals: FloatArray
    function_evaluations: int
    success: bool
    message: str


def _normalized_tangent(
    operator: object,
    ground_state: ComplexArray,
) -> ComplexArray:
    candidate = np.asarray(operator @ ground_state, dtype=complex)
    candidate -= ground_state * np.vdot(ground_state, candidate)
    norm = float(np.linalg.norm(candidate))
    if not np.isfinite(norm) or norm <= 1e-14:
        raise RuntimeError("observable does not generate a nonzero tangent")
    return candidate / norm


def exact_reference_sensitivity(
    parameters: DimerParameters,
    *,
    sample_times: FloatArray,
    phonon_cutoff: int = 16,
    perturbation_amplitudes: tuple[float, ...] = (5e-6, 1e-5),
    direction_names: tuple[str, ...] = DIRECTION_NAMES,
    eigensolver_tolerance: float = 1e-12,
    relative_tolerance: float = 1e-10,
    absolute_tolerance: float = 1e-12,
    maximum_step: float = 0.05,
) -> ExactReferenceSensitivity:
    """Propagate nearby exact states and contract them to 31 coordinates.

    The tangent named ``drive`` is generated by the electronic site-imbalance
    operator coupled to the pulse.  ``relative_phonon_position`` is generated
    by the relative phonon displacement.  Both operators preserve the
    spin-exchange symmetry assumed by the dimer moment equations.
    """

    times = np.asarray(sample_times, dtype=float)
    amplitudes = np.asarray(perturbation_amplitudes, dtype=float)
    if times.ndim != 1 or times.size < 2:
        raise ValueError("sample_times must contain at least two times")
    if abs(float(times[0])) > 1e-15 or np.any(np.diff(times) <= 0.0):
        raise ValueError("sample_times must start at zero and increase")
    if amplitudes.ndim != 1 or amplitudes.size == 0:
        raise ValueError("perturbation_amplitudes must be nonempty")
    if np.any(amplitudes <= 0.0):
        raise ValueError("perturbation amplitudes must be positive")
    if relative_tolerance <= 0.0 or absolute_tolerance <= 0.0:
        raise ValueError("integration tolerances must be positive")
    if maximum_step <= 0.0:
        raise ValueError("maximum_step must be positive")
    if not direction_names:
        raise ValueError("at least one perturbation direction is required")
    unknown = set(direction_names) - set(DIRECTION_NAMES)
    if unknown:
        raise ValueError(f"unknown direction names: {sorted(unknown)}")

    model = _build_exact_dimer_model(
        parameters,
        phonon_cutoff=phonon_cutoff,
    )
    _, ground_state = _ground_state(
        model,
        eigensolver_tolerance=eigensolver_tolerance,
    )
    direction_operators = {
        "drive": model.drive_operator,
        "relative_phonon_position": model.relative_position,
    }
    tangents = tuple(
        _normalized_tangent(direction_operators[name], ground_state)
        for name in direction_names
    )

    initial_basis = np.column_stack((ground_state, *tangents))
    dimension, basis_count = initial_basis.shape

    def rhs(time_value: float, flattened: ComplexArray) -> ComplexArray:
        states = np.asarray(flattened, dtype=complex).reshape(
            dimension,
            basis_count,
        )
        velocities = model.static_hamiltonian @ states
        velocities += parameters.drive_difference(time_value) * (
            model.drive_operator @ states
        )
        return np.asarray(-1j * velocities, dtype=complex).reshape(-1)

    solution = solve_ivp(
        rhs,
        (float(times[0]), float(times[-1])),
        initial_basis.reshape(-1),
        method="DOP853",
        t_eval=times,
        rtol=relative_tolerance,
        atol=absolute_tolerance,
        max_step=maximum_step,
    )
    if not solution.success or solution.y.shape[1] != times.size:
        raise RuntimeError(f"exact sensitivity propagation failed: {solution.message}")

    direction_count = len(direction_names)
    amplitude_count = amplitudes.size
    time_count = times.size
    case_shape = (direction_count, amplitude_count, time_count)
    base_coordinates = np.empty((time_count, 31), dtype=float)
    shadow_coordinates = np.empty(case_shape + (31,), dtype=float)
    euclidean_distances = np.empty(case_shape, dtype=float)
    frobenius_distances = np.empty(case_shape, dtype=float)
    fidelities = np.empty(case_shape, dtype=float)
    chord_distances = np.empty(case_shape, dtype=float)
    raw_shadow_norms = np.empty(case_shape, dtype=float)
    basis_norms = np.empty((basis_count, time_count), dtype=float)
    base_tangent_overlaps = np.empty(
        (direction_count, time_count),
        dtype=complex,
    )
    base_margins = np.empty((time_count, 4), dtype=float)
    shadow_margins = np.empty(case_shape + (4,), dtype=float)
    base_trace_residuals = np.empty(time_count, dtype=float)
    shadow_trace_residuals = np.empty(case_shape, dtype=float)

    for time_index in range(time_count):
        basis = np.asarray(solution.y[:, time_index], dtype=complex).reshape(
            dimension,
            basis_count,
        )
        basis_norms[:, time_index] = np.linalg.norm(basis, axis=0)
        normalized_basis = basis / basis_norms[:, time_index]
        base = normalized_basis[:, 0]
        base_coordinates[time_index] = matrix_state_to_closed_scalar_coordinates(
            _contract_matrix_state(model, base)
        )
        base_margins[time_index], base_trace_residuals[time_index] = (
            physicality_diagnostics(base_coordinates[time_index])
        )

        for direction_index in range(direction_count):
            tangent = normalized_basis[:, direction_index + 1]
            base_tangent_overlaps[direction_index, time_index] = np.vdot(
                base,
                tangent,
            )
            for amplitude_index, amplitude in enumerate(amplitudes):
                raw_shadow = (base + amplitude * tangent) / np.sqrt(
                    1.0 + amplitude * amplitude
                )
                raw_norm = float(np.linalg.norm(raw_shadow))
                raw_shadow_norms[
                    direction_index,
                    amplitude_index,
                    time_index,
                ] = raw_norm
                shadow = raw_shadow / raw_norm
                overlap = np.vdot(base, shadow)
                fidelity = min(1.0, float(abs(overlap) ** 2))
                fidelities[
                    direction_index,
                    amplitude_index,
                    time_index,
                ] = fidelity
                chord_distances[
                    direction_index,
                    amplitude_index,
                    time_index,
                ] = np.sqrt(max(0.0, 2.0 - 2.0 * np.sqrt(fidelity)))

                coordinates = matrix_state_to_closed_scalar_coordinates(
                    _contract_matrix_state(model, shadow)
                )
                shadow_coordinates[
                    direction_index,
                    amplitude_index,
                    time_index,
                ] = coordinates
                delta = coordinates - base_coordinates[time_index]
                euclidean_distances[
                    direction_index,
                    amplitude_index,
                    time_index,
                ] = float(np.linalg.norm(delta))
                frobenius_distances[
                    direction_index,
                    amplitude_index,
                    time_index,
                ] = closed_state_lifted_frobenius_norm(delta)
                (
                    shadow_margins[
                        direction_index,
                        amplitude_index,
                        time_index,
                    ],
                    shadow_trace_residuals[
                        direction_index,
                        amplitude_index,
                        time_index,
                    ],
                ) = physicality_diagnostics(coordinates)

    return ExactReferenceSensitivity(
        times=np.asarray(solution.t, dtype=float),
        direction_names=tuple(direction_names),
        perturbation_amplitudes=amplitudes,
        base_coordinates=base_coordinates,
        shadow_coordinates=shadow_coordinates,
        coordinate_euclidean_distances=euclidean_distances,
        coordinate_frobenius_distances=frobenius_distances,
        state_fidelities=fidelities,
        state_chord_distances=chord_distances,
        raw_shadow_norms=raw_shadow_norms,
        basis_norms=basis_norms,
        base_tangent_overlaps=base_tangent_overlaps,
        base_margins=base_margins,
        shadow_margins=shadow_margins,
        base_trace_residuals=base_trace_residuals,
        shadow_trace_residuals=shadow_trace_residuals,
        function_evaluations=int(solution.nfev),
        success=bool(solution.success),
        message=str(solution.message),
    )


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _write_json_atomic(path: Path, payload: dict[str, object]) -> None:
    temporary = path.with_name(path.name + ".tmp")
    with temporary.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2, sort_keys=True)
        handle.write("\n")
        handle.flush()
        os.fsync(handle.fileno())
    os.replace(temporary, path)


def _case_summary(
    result: ExactReferenceSensitivity,
    direction_index: int,
    amplitude_index: int,
) -> dict[str, object]:
    distances = result.coordinate_frobenius_distances[
        direction_index,
        amplitude_index,
    ]
    initial_distance = float(distances[0])
    final_time = float(result.times[-1])
    late_start = min(40.0, 0.4 * final_time)
    late_index = int(np.searchsorted(result.times, late_start))
    late_duration = final_time - float(result.times[late_index])
    late_endpoint_rate = (
        float(np.log(distances[-1] / distances[late_index]) / late_duration)
        if late_duration > 0.0
        else None
    )
    fidelity = result.state_fidelities[direction_index, amplitude_index]
    margins = result.shadow_margins[direction_index, amplitude_index]
    return {
        "direction": result.direction_names[direction_index],
        "wavefunction_perturbation_amplitude": float(
            result.perturbation_amplitudes[amplitude_index]
        ),
        "initial_contracted_frobenius_distance": initial_distance,
        "maximum_contracted_frobenius_distance": float(np.max(distances)),
        "final_contracted_frobenius_distance": float(distances[-1]),
        "maximum_contracted_amplification": float(
            np.max(distances) / initial_distance
        ),
        "final_contracted_amplification": float(
            distances[-1] / initial_distance
        ),
        "late_window_start": float(result.times[late_index]),
        "late_window_endpoint_log_rate": late_endpoint_rate,
        "initial_state_fidelity": float(fidelity[0]),
        "maximum_state_fidelity_drift": float(
            np.max(np.abs(fidelity - fidelity[0]))
        ),
        "maximum_raw_shadow_norm_drift": float(
            np.max(
                np.abs(
                    result.raw_shadow_norms[
                        direction_index,
                        amplitude_index,
                    ]
                    - 1.0
                )
            )
        ),
        "minimum_joint_gram_margin": float(np.min(margins[:, 3])),
        "maximum_correlation_trace_residual": float(
            np.max(
                result.shadow_trace_residuals[
                    direction_index,
                    amplitude_index,
                ]
            )
        ),
    }


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--cutoffs", type=int, nargs="+", default=[12, 16, 20])
    parser.add_argument("--final-time", type=float, default=100.0)
    parser.add_argument("--sample-step", type=float, default=0.1)
    parser.add_argument("--maximum-step", type=float, default=0.05)
    parser.add_argument("--relative-tolerance", type=float, default=1e-10)
    parser.add_argument("--absolute-tolerance", type=float, default=1e-12)
    parser.add_argument(
        "--perturbation-amplitudes",
        type=float,
        nargs="+",
        default=[5e-6, 1e-5],
    )
    return parser


def main() -> int:
    args = _parser().parse_args()
    if args.final_time <= 0.0 or args.sample_step <= 0.0:
        raise SystemExit("final-time and sample-step must be positive")
    interval_count = int(round(args.final_time / args.sample_step))
    if not np.isclose(
        interval_count * args.sample_step,
        args.final_time,
        rtol=0.0,
        atol=1e-12,
    ):
        raise SystemExit("sample-step must divide final-time")
    args.output_dir.mkdir(parents=True, exist_ok=True)
    parameters = DimerParameters(
        hopping=1.0,
        gamma=0.5,
        lambda_ep=1.5,
        drive_amplitude=1.0,
        pulse_width=1.0,
    )
    times = np.linspace(0.0, args.final_time, interval_count + 1)
    source_dir = Path(__file__).resolve().parent
    plan = {
        "schema": "paper_v_exact_reference_sensitivity_plan_v1",
        "classification": "diagnostic",
        "evidence_status": "exploratory_local_not_promoted",
        "scientific_question": (
            "Does exact unitary evolution amplify nearby physical states in "
            "the contracted 31-coordinate moment representation?"
        ),
        "parameters": {
            "hopping": parameters.hopping,
            "gamma": parameters.gamma,
            "lambda_ep": parameters.lambda_ep,
            "drive_amplitude": parameters.drive_amplitude,
            "pulse_width": parameters.pulse_width,
            "phonon_cutoffs": list(args.cutoffs),
        },
        "initial_state": "exact zero-field truncated-Hamiltonian ground state",
        "perturbations": {
            "directions": list(DIRECTION_NAMES),
            "wavefunction_amplitudes": list(args.perturbation_amplitudes),
            "construction": "normalized observable tangent orthogonal to ground state",
        },
        "integration": {
            "method": "adaptive DOP853",
            "final_time": args.final_time,
            "sample_step": args.sample_step,
            "maximum_step": args.maximum_step,
            "relative_tolerance": args.relative_tolerance,
            "absolute_tolerance": args.absolute_tolerance,
        },
        "interpretation_contract": {
            "wavefunction_fidelity": "constant under the common unitary flow",
            "contracted_distance_growth": (
                "finite-time amplification of retained observables, not "
                "full-state chaos"
            ),
            "trajectory_rescaling": "none",
        },
        "source_sha256": {
            "analysis": _sha256(Path(__file__).resolve()),
            "exact_reference": _sha256(source_dir / "exact_reference.py"),
            "matrix_reference": _sha256(source_dir / "matrix_reference.py"),
        },
    }
    _write_json_atomic(args.output_dir / "plan.json", plan)

    cutoff_summaries: dict[str, object] = {}
    for cutoff in args.cutoffs:
        result = exact_reference_sensitivity(
            parameters,
            sample_times=times,
            phonon_cutoff=cutoff,
            perturbation_amplitudes=tuple(args.perturbation_amplitudes),
            relative_tolerance=args.relative_tolerance,
            absolute_tolerance=args.absolute_tolerance,
            maximum_step=args.maximum_step,
        )
        np.savez_compressed(
            args.output_dir / f"trajectory_cutoff_{cutoff}.npz",
            times=result.times,
            direction_names=np.asarray(result.direction_names),
            perturbation_amplitudes=result.perturbation_amplitudes,
            base_coordinates=result.base_coordinates,
            shadow_coordinates=result.shadow_coordinates,
            coordinate_euclidean_distances=(
                result.coordinate_euclidean_distances
            ),
            coordinate_frobenius_distances=(
                result.coordinate_frobenius_distances
            ),
            state_fidelities=result.state_fidelities,
            state_chord_distances=result.state_chord_distances,
            raw_shadow_norms=result.raw_shadow_norms,
            basis_norms=result.basis_norms,
            base_tangent_overlaps=result.base_tangent_overlaps,
            base_margins=result.base_margins,
            shadow_margins=result.shadow_margins,
            base_trace_residuals=result.base_trace_residuals,
            shadow_trace_residuals=result.shadow_trace_residuals,
        )
        cases = [
            _case_summary(result, direction_index, amplitude_index)
            for direction_index in range(len(result.direction_names))
            for amplitude_index in range(result.perturbation_amplitudes.size)
        ]
        cutoff_summaries[str(cutoff)] = {
            "function_evaluations": result.function_evaluations,
            "maximum_basis_norm_drift": float(
                np.max(np.abs(result.basis_norms - 1.0))
            ),
            "maximum_base_tangent_overlap": float(
                np.max(np.abs(result.base_tangent_overlaps))
            ),
            "minimum_base_joint_gram_margin": float(
                np.min(result.base_margins[:, 3])
            ),
            "cases": cases,
        }
        print(
            json.dumps(
                {
                    "recorded_at_utc": datetime.now(timezone.utc).isoformat(),
                    "cutoff": cutoff,
                    "status": "complete",
                    "function_evaluations": result.function_evaluations,
                },
                sort_keys=True,
            ),
            flush=True,
        )

    summary = {
        "schema": "paper_v_exact_reference_sensitivity_summary_v1",
        "status": "complete",
        "classification": "diagnostic",
        "evidence_status": "exploratory_local_not_promoted",
        "cutoffs": cutoff_summaries,
        "interpretation": (
            "The common exact Hamiltonian flow is tested by fidelity "
            "conservation. Contracted 31-coordinate amplification is reported "
            "separately and is not a full-state Lyapunov exponent."
        ),
    }
    _write_json_atomic(args.output_dir / "summary.json", summary)
    print(json.dumps(summary, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
