"""Drive-aware word-Hankel lower bound for the raw Holstein moment chart.

The retained space is the verified 29-dimensional Hilbert--Schmidt basis from
``krylov_memory_closure``.  This module audits the unresolved force channel
generated by every word in the static and drive Liouvillians.  It does not fit
or propagate an autonomous closure and it never consumes an exact trajectory.

For skew-adjoint component generators, the unresolved input blocks
``G_i = Q A_i R`` and output blocks ``C_i = -G_i.T`` have matching word spans.
Consequently, when the left and right word sets contain every component word
through the same depth, the corresponding force-channel Hankel rank equals
the rank of the generated word span.  Preparation columns can only enlarge
the full reachability space, so this force-channel rank is a preparation-
independent lower bound on the hidden order requested by the memorandum.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass

import numpy as np
from numpy.typing import NDArray
from scipy.sparse import csc_matrix, eye

from .hubbard_dimer import DimerParameters
from .krylov_memory_closure import (
    KrylovClosureConstruction,
    OperatorBlock,
    _apply_liouvillian,
    _operator_block_norm,
    _orthonormalize_block,
    build_krylov_closure_construction,
)

FloatArray = NDArray[np.float64]
ComplexArray = NDArray[np.complex128]


@dataclass(frozen=True)
class ComponentWordEnvelope:
    """Nested static/drive Liouvillian word layers without a dimension cap."""

    construction: KrylovClosureConstruction
    maximum_word_depth: int
    rank_tolerance: float
    drive_component_scale: float
    layers: tuple[OperatorBlock, ...]
    layer_singular_values: tuple[FloatArray, ...]

    @property
    def layer_dimensions(self) -> tuple[int, ...]:
        return tuple(len(layer) for layer in self.layers)

    @property
    def cumulative_dimensions(self) -> tuple[int, ...]:
        total = 0
        values = []
        for layer in self.layers:
            total += len(layer)
            values.append(total)
        return tuple(values)

    @property
    def hidden_observables(self) -> OperatorBlock:
        return tuple(operator for layer in self.layers for operator in layer)


@dataclass(frozen=True)
class WordHankelRankAudit:
    """Nested force-channel word ranks for one cutoff and tolerance."""

    phonon_cutoff: int
    hilbert_dimension: int
    rank_tolerance: float
    practical_hidden_budget: int
    maximum_word_depth: int
    drive_component_scale: float
    static_force_norm: float
    drive_force_norm: float
    new_ranks: tuple[int, ...]
    cumulative_ranks: tuple[int, ...]
    frontier_singular_values: tuple[FloatArray, ...]

    @property
    def evaluated_word_depth(self) -> int:
        return len(self.cumulative_ranks) - 1

    @property
    def hankel_rank_lower_bound(self) -> int:
        if not self.cumulative_ranks:
            return 0
        return self.cumulative_ranks[-1]

    @property
    def crossed_budget(self) -> bool:
        return self.hankel_rank_lower_bound > self.practical_hidden_budget

    @property
    def first_budget_crossing_depth(self) -> int | None:
        for depth, rank in enumerate(self.cumulative_ranks):
            if rank > self.practical_hidden_budget:
                return depth
        return None

    def summary(self) -> dict[str, object]:
        """Return a JSON-compatible scientific summary."""

        return {
            "phonon_cutoff": self.phonon_cutoff,
            "hilbert_dimension": self.hilbert_dimension,
            "rank_tolerance": self.rank_tolerance,
            "practical_hidden_budget": self.practical_hidden_budget,
            "maximum_word_depth": self.maximum_word_depth,
            "evaluated_word_depth": self.evaluated_word_depth,
            "drive_component_scale": self.drive_component_scale,
            "static_force_norm": self.static_force_norm,
            "drive_force_norm": self.drive_force_norm,
            "new_ranks": list(self.new_ranks),
            "cumulative_ranks": list(self.cumulative_ranks),
            "hankel_rank_lower_bound": self.hankel_rank_lower_bound,
            "crossed_budget": self.crossed_budget,
            "first_budget_crossing_depth": self.first_budget_crossing_depth,
            "frontier_singular_values": [
                values.tolist() for values in self.frontier_singular_values
            ],
        }


def _scaled_block(
    operators: OperatorBlock,
    scale: float,
) -> OperatorBlock:
    if scale == 1.0:
        return operators
    return tuple((scale * operator).tocsc() for operator in operators)


def _preparation_density_candidates(
    state_vectors: Sequence[ComplexArray],
    construction: KrylovClosureConstruction,
) -> OperatorBlock:
    """Return traceless preparation densities before frame residualization.

    A preparation contributes only once, through its initial density operator.
    Removing ``I / d`` makes the candidate traceless; the subsequent common
    orthogonalization removes the 29 retained raw-moment directions.  Hence the
    surviving column is precisely the unresolved initial component required by
    the Route-4 initial-slip construction.
    """

    dimension = construction.hilbert_dimension
    identity_density = eye(
        dimension,
        format="csc",
        dtype=complex,
    ) / float(dimension)
    candidates = []
    for state_vector in state_vectors:
        state = np.asarray(state_vector, dtype=complex)
        if state.shape != (dimension,):
            raise ValueError("preparation state has incompatible Hilbert dimension")
        norm = float(np.linalg.norm(state))
        if not np.isfinite(norm) or norm == 0.0:
            raise ValueError("preparation state must have finite nonzero norm")
        normalized = state / norm
        density = csc_matrix(np.outer(normalized, normalized.conjugate()))
        candidates.append((density - identity_density).tocsc())
    return tuple(candidates)


def build_drive_aware_word_envelope(
    parameters: DimerParameters,
    *,
    phonon_cutoff: int,
    maximum_word_depth: int,
    rank_tolerance: float = 1e-11,
    drive_component_scale: float = 1.0,
    preparation_state_vectors: Sequence[ComplexArray] = (),
) -> ComponentWordEnvelope:
    """Build the complete nested component-word envelope through one depth.

    Depth zero is the orthonormal union of ``Q L_static R``,
    ``Q L_drive R``, and any declared preparation-density residuals.  Every
    subsequent layer applies both unresolved component Liouvillians to the
    newest layer and removes the raw frame and all earlier hidden layers.
    Unlike the historical budget audit, this constructor has no scientific
    dimension cap.
    """

    if phonon_cutoff < 2:
        raise ValueError("phonon_cutoff must be at least two for the raw chart")
    if maximum_word_depth < 0:
        raise ValueError("maximum_word_depth must be nonnegative")
    if not 0.0 < rank_tolerance < 1.0:
        raise ValueError("rank_tolerance must lie between zero and one")
    if not np.isfinite(drive_component_scale) or drive_component_scale <= 0.0:
        raise ValueError("drive_component_scale must be finite and positive")

    construction = build_krylov_closure_construction(
        parameters,
        phonon_cutoff=phonon_cutoff,
        shell_count=1,
        rank_tolerance=rank_tolerance,
    )
    retained = construction.raw_basis.orthonormal_observables
    dimension = construction.hilbert_dimension
    scaled_drive_hamiltonian = (
        drive_component_scale * construction.drive_hamiltonian
    ).tocsc()
    scaled_drive_force = _scaled_block(
        construction.drive_force,
        drive_component_scale,
    )
    first_layer, first_values = _orthonormalize_block(
        (*construction.static_force, *scaled_drive_force),
        retained,
        dimension=dimension,
        rank_tolerance=rank_tolerance,
    )
    force_layers: list[OperatorBlock] = []
    force_singular_values: list[FloatArray] = []
    if first_layer:
        force_layers.append(first_layer)
        force_singular_values.append(first_values)
    while force_layers and len(force_layers) <= maximum_word_depth:
        hidden = tuple(
            operator for layer in force_layers for operator in layer
        )
        candidates = (
            *_apply_liouvillian(
                construction.static_hamiltonian,
                force_layers[-1],
            ),
            *_apply_liouvillian(
                scaled_drive_hamiltonian,
                force_layers[-1],
            ),
        )
        layer, values = _orthonormalize_block(
            candidates,
            (*retained, *hidden),
            dimension=dimension,
            rank_tolerance=rank_tolerance,
        )
        if not layer:
            break
        force_layers.append(layer)
        force_singular_values.append(values)

    # Keep the low-rank preparation branch separate from the sparse force
    # branch.  A joint SVD would mix one dense density residual into every
    # force column, turning the complete word envelope dense at cutoff 16.
    # Sequential residualization spans the same declared union while retaining
    # only the genuinely preparation-derived columns as dense operators.
    force_hidden = tuple(
        operator for layer in force_layers for operator in layer
    )
    preparation_layers: list[OperatorBlock] = []
    preparation_singular_values: list[FloatArray] = []
    preparation_candidates = _preparation_density_candidates(
        preparation_state_vectors,
        construction,
    )
    if preparation_candidates:
        preparation_layer, values = _orthonormalize_block(
            preparation_candidates,
            (*retained, *force_hidden),
            dimension=dimension,
            rank_tolerance=rank_tolerance,
        )
        if preparation_layer:
            preparation_layers.append(preparation_layer)
            preparation_singular_values.append(values)
    while (
        preparation_layers
        and len(preparation_layers) <= maximum_word_depth
    ):
        preparation_hidden = tuple(
            operator
            for layer in preparation_layers
            for operator in layer
        )
        candidates = (
            *_apply_liouvillian(
                construction.static_hamiltonian,
                preparation_layers[-1],
            ),
            *_apply_liouvillian(
                scaled_drive_hamiltonian,
                preparation_layers[-1],
            ),
        )
        preparation_layer, values = _orthonormalize_block(
            candidates,
            (*retained, *force_hidden, *preparation_hidden),
            dimension=dimension,
            rank_tolerance=rank_tolerance,
        )
        if not preparation_layer:
            break
        preparation_layers.append(preparation_layer)
        preparation_singular_values.append(values)

    layer_count = max(len(force_layers), len(preparation_layers))
    layers = tuple(
        (
            *(force_layers[index] if index < len(force_layers) else ()),
            *(
                preparation_layers[index]
                if index < len(preparation_layers)
                else ()
            ),
        )
        for index in range(layer_count)
    )
    singular_values = tuple(
        np.concatenate(
            (
                force_singular_values[index]
                if index < len(force_singular_values)
                else np.empty(0, dtype=float),
                preparation_singular_values[index]
                if index < len(preparation_singular_values)
                else np.empty(0, dtype=float),
            )
        )
        for index in range(layer_count)
    )

    return ComponentWordEnvelope(
        construction=construction,
        maximum_word_depth=maximum_word_depth,
        rank_tolerance=rank_tolerance,
        drive_component_scale=drive_component_scale,
        layers=layers,
        layer_singular_values=singular_values,
    )


def drive_aware_word_hankel_rank_audit(
    parameters: DimerParameters,
    *,
    phonon_cutoff: int,
    maximum_word_depth: int = 3,
    rank_tolerance: float = 1e-11,
    practical_hidden_budget: int = 96,
    drive_component_scale: float = 1.0,
) -> WordHankelRankAudit:
    """Measure the nested generalized-Hankel rank lower bound.

    Depth zero contains the unresolved component forces ``Q A_i R``.  Each
    later depth applies both ``Q A_0 Q`` and ``Q A_1 Q`` to the newest
    quotient space.  Block Arnoldi orthogonalization removes the resolved
    directions and all previously generated hidden directions.  The resulting
    cumulative dimension is exactly the rank of the force-channel word Hankel
    matrix for equal complete left/right word sets through that depth.

    The computation stops as soon as the practical hidden budget is exceeded,
    because preparation channels cannot lower this rank.
    """

    if phonon_cutoff < 2:
        raise ValueError("phonon_cutoff must be at least two for the raw chart")
    if maximum_word_depth < 0:
        raise ValueError("maximum_word_depth must be nonnegative")
    if not 0.0 < rank_tolerance < 1.0:
        raise ValueError("rank_tolerance must lie between zero and one")
    if practical_hidden_budget <= 0:
        raise ValueError("practical_hidden_budget must be positive")
    if not np.isfinite(drive_component_scale) or drive_component_scale <= 0.0:
        raise ValueError("drive_component_scale must be finite and positive")

    construction = build_krylov_closure_construction(
        parameters,
        phonon_cutoff=phonon_cutoff,
        shell_count=1,
        rank_tolerance=rank_tolerance,
    )
    retained = construction.raw_basis.orthonormal_observables
    dimension = construction.hilbert_dimension
    scaled_drive_hamiltonian = (
        drive_component_scale * construction.drive_hamiltonian
    ).tocsc()
    scaled_drive_force = _scaled_block(
        construction.drive_force,
        drive_component_scale,
    )

    frontier, singular_values = _orthonormalize_block(
        (*construction.static_force, *scaled_drive_force),
        retained,
        dimension=dimension,
        rank_tolerance=rank_tolerance,
    )
    hidden_basis: list = []
    new_ranks: list[int] = []
    cumulative_ranks: list[int] = []
    frontier_values: list[FloatArray] = []

    for depth in range(maximum_word_depth + 1):
        new_ranks.append(len(frontier))
        hidden_basis.extend(frontier)
        cumulative_ranks.append(len(hidden_basis))
        frontier_values.append(np.asarray(singular_values, dtype=float))
        if not frontier or len(hidden_basis) > practical_hidden_budget:
            break
        if depth == maximum_word_depth:
            break

        candidates = (
            *_apply_liouvillian(construction.static_hamiltonian, frontier),
            *_apply_liouvillian(scaled_drive_hamiltonian, frontier),
        )
        frontier, singular_values = _orthonormalize_block(
            candidates,
            (*retained, *hidden_basis),
            dimension=dimension,
            rank_tolerance=rank_tolerance,
        )

    return WordHankelRankAudit(
        phonon_cutoff=phonon_cutoff,
        hilbert_dimension=dimension,
        rank_tolerance=rank_tolerance,
        practical_hidden_budget=practical_hidden_budget,
        maximum_word_depth=maximum_word_depth,
        drive_component_scale=drive_component_scale,
        static_force_norm=_operator_block_norm(
            construction.static_force,
            dimension=dimension,
        ),
        drive_force_norm=_operator_block_norm(
            scaled_drive_force,
            dimension=dimension,
        ),
        new_ranks=tuple(new_ranks),
        cumulative_ranks=tuple(cumulative_ranks),
        frontier_singular_values=tuple(frontier_values),
    )
